import Link from "next/link";
import {redirect} from "next/navigation";
import {requireBuildPulseWorkforce} from "@/lib/buildpulse/workforce-auth";
import {createAdminClient} from "@/lib/supabase/admin";
import {AgentApprovalActions} from "@/components/buildpulse/AgentApprovalActions";
import {LocalizationReviewActions} from "@/components/buildpulse/LocalizationReviewActions";

export const metadata={title:"Control Plane | BuildPulse",robots:{index:false,follow:false}};

export default async function ControlPlane(){
 const auth=await requireBuildPulseWorkforce(["founder","admin","engineering","editorial","finance","advertising","moderation","support","analyst"]);
 if(!auth.ok)redirect(auth.reason==="mfa_required"?"/auth/mfa?next=/workforce/control":"/auth?next=/workforce/control");
 const db=createAdminClient();if(!db)throw new Error("Control plane unavailable");
 const since=new Date(Date.now()-24*3600*1000).toISOString();
 const [{data:agents},{data:runs},{data:jobs},{data:approvals},{data:localizations},{data:schedules},{data:usage},{data:budgets},{count:review},{count:subs},{count:ads}]=await Promise.all([
  db.from("buildpulse_agents").select("id,code,name,domain,autonomy_level,enabled,description,schedule_hint").order("domain"),
  db.from("buildpulse_agent_runs").select("id,status,summary,error,created_at,buildpulse_agents(name)").order("created_at",{ascending:false}).limit(12),
  db.from("buildpulse_job_runs").select("job_name,status,started_at,finished_at,error").order("started_at",{ascending:false}).limit(12),
  db.from("buildpulse_agent_approvals").select("id,run_id,action_key,risk_level,state,requested_at,buildpulse_agent_runs(summary,buildpulse_agents(name))").eq("state","pending").order("requested_at",{ascending:true}).limit(20),
  db.from("buildpulse_story_localizations").select("id,story_id,locale,title,summary,source_language,provider,model,created_at,buildpulse_stories(title,canonical_source_url,buildpulse_sources(name,country_code,region_name,city_name))").eq("translation_state","review").order("created_at",{ascending:true}).limit(20),
  db.from("buildpulse_agent_schedules").select("id,name,cadence,hour_utc,day_of_week,enabled,last_run_at,next_run_at,last_run_status,buildpulse_agents(name,code)").order("next_run_at",{ascending:true,nullsFirst:false}).limit(30),
  db.from("buildpulse_ai_usage_events").select("task,provider,model,status,total_tokens,duration_ms,created_at").gte("created_at",since).order("created_at",{ascending:false}).limit(200),
  db.from("buildpulse_ai_budgets").select("task,daily_token_limit,daily_request_limit,enabled").order("task"),
  db.from("buildpulse_stories").select("id",{head:true,count:"exact"}).in("verification_state",["pending","needs_review"]),
  db.from("buildpulse_subscribers").select("id",{head:true,count:"exact"}).eq("status","active"),
  db.from("buildpulse_ad_orders").select("id",{head:true,count:"exact"}).in("status",["submitted","scheduled","active"])
 ]);
 const u=usage??[],requests=u.filter((x:any)=>x.status==="success").length,failures=u.filter((x:any)=>x.status==="failure").length,tokens=u.reduce((n:number,x:any)=>n+Number(x.total_tokens??0),0);
 const cards=[["Review queue",review??0,"/admin/stories"],["Active subscribers",subs??0,"/subscriptions"],["Ad operations",ads??0,"/admin/advertising"],["Workforce",auth.roles.join(", "),"/workforce"]];
 return <main className="min-h-screen bg-[#f3f5f4] text-slate-950"><div className="mx-auto max-w-[1600px] px-5 py-8">
  <header className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-300 pb-6"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#0b6b63]">BuildPulse Control Plane</p><h1 className="mt-2 text-4xl font-black tracking-tight">Operations command center</h1><p className="mt-2 text-sm text-slate-500">{auth.profile.display_name} · {auth.profile.department||"BuildPulse"} · MFA-protected, role-scoped session</p></div><Link href="/workforce" className="rounded-full border bg-white px-5 py-3 text-sm font-bold">Workforce home</Link></header>
  <section className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{cards.map(([n,v,h])=><Link href={String(h)} key={String(n)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{n}</p><p className="mt-3 text-2xl font-black">{v}</p></Link>)}</section>
  <section className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">AI requests · 24h</p><p className="mt-2 text-3xl font-black">{requests}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">AI tokens · 24h</p><p className="mt-2 text-3xl font-black">{tokens.toLocaleString("en-US")}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">AI failures · 24h</p><p className="mt-2 text-3xl font-black">{failures}</p></div></section>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
   <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">AI Operations</p><h2 className="mt-1 text-2xl font-black">Agent fleet</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{agents?.filter((x:any)=>x.enabled).length??0} enabled</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{(agents??[]).map((a:any)=><article key={a.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><strong>{a.name}</strong><span className="text-xs font-bold uppercase text-slate-500">{a.autonomy_level.replaceAll("_"," ")}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{a.description}</p><p className="mt-3 text-[11px] font-bold uppercase tracking-wide text-slate-400">{a.domain} · {a.schedule_hint||"manual"}</p></article>)}</div></section>
   <section className="rounded-3xl border bg-slate-950 p-6 text-white shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-emerald-300">Automation health</p><h2 className="mt-1 text-2xl font-black">Recent jobs</h2><div className="mt-5 space-y-3">{(jobs??[]).map((j:any,i:number)=><div key={i} className="border-b border-white/10 pb-3"><div className="flex justify-between gap-3 text-sm"><strong>{j.job_name}</strong><span className={j.status==="ok"?"text-emerald-300":j.status==="failed"?"text-red-300":"text-amber-200"}>{j.status}</span></div><p className="mt-1 text-xs text-white/45">{new Date(j.started_at).toLocaleString("en-GB",{timeZone:"UTC"})} UTC</p></div>)}</div></section>
  </div>
  <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Schedules</p><h2 className="mt-1 text-2xl font-black">Automation cadence</h2></div><span className="text-xs font-bold text-slate-500">Atomic claims · fail-closed</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Agent</th><th>Schedule</th><th>Cadence</th><th>Last</th><th>Next</th><th>State</th></tr></thead><tbody>{(schedules??[]).map((s:any)=><tr key={s.id} className="border-b"><td className="py-4 font-bold">{s.buildpulse_agents?.name||"Agent"}</td><td>{s.name}</td><td>{s.cadence}</td><td>{s.last_run_at?new Date(s.last_run_at).toLocaleString("en-GB",{timeZone:"UTC"}):"—"}</td><td>{s.next_run_at?new Date(s.next_run_at).toLocaleString("en-GB",{timeZone:"UTC"}):"—"}</td><td>{s.enabled?(s.last_run_status||"ready"):"disabled"}</td></tr>)}</tbody></table></div></section>
  <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Approval inbox</p><h2 className="mt-1 text-2xl font-black">AI decisions requiring a person</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-800">{approvals?.length??0} pending</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{(approvals??[]).map((a:any)=><article key={a.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{a.buildpulse_agent_runs?.buildpulse_agents?.name||"Agent"}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase">{a.risk_level}</span></div><p className="mt-2 text-xs font-bold uppercase tracking-wide text-slate-400">{a.action_key}</p><p className="mt-3 max-h-32 overflow-auto text-sm leading-6 text-slate-600">{a.buildpulse_agent_runs?.summary||"No summary available."}</p><AgentApprovalActions approvalId={a.id}/></article>)}</div></section>
  <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Localization review</p><h2 className="mt-1 text-2xl font-black">Local-language stories awaiting approval</h2></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-black text-sky-800">{localizations?.length??0} pending</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{(localizations??[]).map((l:any)=><article key={l.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{l.locale.toUpperCase()} · {l.buildpulse_stories?.buildpulse_sources?.name||"Source"}</strong><span className="text-[10px] font-black uppercase text-slate-400">{l.provider||"AI"} · {l.model||"model"}</span></div><p className="mt-2 text-xs text-slate-500">Original: {l.buildpulse_stories?.title||"—"}</p><h3 className="mt-3 text-lg font-black">{l.title}</h3><p className="mt-2 max-h-32 overflow-auto text-sm leading-6 text-slate-600">{l.summary||"—"}</p>{l.buildpulse_stories?.canonical_source_url&&<a href={l.buildpulse_stories.canonical_source_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-black underline">Open canonical source ↗</a>}<LocalizationReviewActions localizationId={l.id}/></article>)}</div></section><section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">AI budgets</p><h2 className="mt-1 text-2xl font-black">Task limits</h2><div className="mt-4 space-y-2">{(budgets??[]).map((b:any)=><div key={b.task} className="flex justify-between gap-4 border-b py-3 text-sm"><strong>{b.task}</strong><span className="text-right text-slate-500">{b.enabled?"enabled":"disabled"} · {b.daily_request_limit??"∞"} req · {b.daily_token_limit??"∞"} tokens/day</span></div>)}</div></div><div className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">AI providers</p><h2 className="mt-1 text-2xl font-black">Last 24 hours</h2><div className="mt-4 space-y-2">{Array.from(new Set(u.map((x:any)=>x.provider))).map((provider:any)=>{const rows=u.filter((x:any)=>x.provider===provider);return <div key={provider} className="flex justify-between border-b py-3 text-sm"><strong>{provider}</strong><span className="text-slate-500">{rows.filter((x:any)=>x.status==="success").length} ok · {rows.filter((x:any)=>x.status==="failure").length} failed</span></div>})}</div></div></section>
  <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Agent audit</p><h2 className="mt-1 text-2xl font-black">Latest runs</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Agent</th><th>Status</th><th>Summary</th><th>Time</th></tr></thead><tbody>{(runs??[]).map((r:any)=><tr key={r.id} className="border-b"><td className="py-4 font-bold">{r.buildpulse_agents?.name||"Agent"}</td><td>{r.status}</td><td className="max-w-xl text-slate-600">{r.summary||r.error||"—"}</td><td>{new Date(r.created_at).toLocaleString("en-GB",{timeZone:"UTC"})}</td></tr>)}</tbody></table></div></section>
 </div></main>
}