"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {formatLocalCurrency,getBuildPulseContext} from "@/lib/buildpulse/localization";
type Product={code:string;name:string;placement:string;width_px:number|null;height_px:number|null;max_copy_chars:number;price_usd:number;duration_days:number};
const countries=[["GLOBAL","Global · all countries"],["GB","United Kingdom"],["DE","Germany"],["TR","Türkiye"],["US","United States"],["AE","United Arab Emirates"],["CH","Switzerland"],["FR","France"],["IT","Italy"],["ES","Spain"],["NL","Netherlands"],["JP","Japan"],["CA","Canada"],["AU","Australia"]];
const currencies=["USD","EUR","GBP","TRY","CHF","JPY"];const localCurrency:Record<string,string>={GB:"GBP",DE:"EUR",TR:"TRY",US:"USD",CH:"CHF",FR:"EUR",IT:"EUR",ES:"EUR",NL:"EUR",JP:"JPY"};
export function AdvertisingInventory({products}:{products:Product[]}){const [country,setCountry]=useState("GLOBAL"),[currency,setCurrency]=useState("USD"),[rates,setRates]=useState<Record<string,number>>({USD:1}),[asOf,setAsOf]=useState("");
useEffect(()=>{try{const c=localStorage.getItem("buildpulse.adMarket")||getBuildPulseContext()?.country||"GLOBAL";setCountry(c);setCurrency(localStorage.getItem("buildpulse.adCurrency")||localCurrency[c]||"USD")}catch{}},[]);
useEffect(()=>{fetch("/api/buildpulse/markets?group=fx").then(r=>r.json()).then(j=>{const n:Record<string,number>={USD:1};for(const q of j.quotes||[]){if(q.symbol==="EUR/USD")n.EUR=1/Number(q.numericValue);if(q.symbol==="GBP/USD")n.GBP=1/Number(q.numericValue);if(q.symbol==="USD/TRY")n.TRY=Number(q.numericValue);if(q.symbol==="USD/CHF")n.CHF=Number(q.numericValue);if(q.symbol==="USD/JPY")n.JPY=Number(q.numericValue)}setRates(n);setAsOf(j.asOf||"")}).catch(()=>{})},[]);
const rate=rates[currency];function countryChange(v:string){setCountry(v);try{localStorage.setItem("buildpulse.adMarket",v)}catch{}const x=localCurrency[v];if(x){setCurrency(x);try{localStorage.setItem("buildpulse.adCurrency",x)}catch{}}}function currencyChange(v:string){setCurrency(v);try{localStorage.setItem("buildpulse.adCurrency",v)}catch{}}
return <><div className="mt-10 grid gap-4 rounded-2xl border border-[#17202a]/15 bg-white p-6 md:grid-cols-2"><label className="text-sm font-black">Billboard country / market<select className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" value={country} onChange={e=>countryChange(e.target.value)}>{countries.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="text-sm font-black">Display currency<select className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" value={currency} onChange={e=>currencyChange(e.target.value)}>{currencies.map(x=><option key={x}>{x}</option>)}</select></label><p className="text-sm leading-6 text-[#53606b] md:col-span-2">Display conversion uses BuildPulse FX reference data. USD remains the configured inventory and checkout base price.{asOf?" Reference feed refreshed "+new Date(asOf).toLocaleString()+".":""}</p></div><div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{products.map(x=><article key={x.code} className="rounded-2xl border border-[#17202a]/15 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-[#65717c]">{x.placement.replaceAll("_"," ")}</p><h2 className="mt-2 text-2xl font-black">{x.name}</h2><p className="mt-3 text-sm text-[#53606b]">{x.width_px&&x.height_px?`${x.width_px} × ${x.height_px}px · `:""}up to {x.max_copy_chars} characters · {x.duration_days} day{x.duration_days===1?"":"s"}</p><p className="mt-5 text-3xl font-black">{rate?formatLocalCurrency(Number(x.price_usd)*rate,currency,{maximumFractionDigits:0}):formatLocalCurrency(Number(x.price_usd),"USD",{maximumFractionDigits:0})}</p>{currency!=="USD"&&<p className="mt-1 text-xs text-[#65717c]">Base price {formatLocalCurrency(Number(x.price_usd),"USD",{maximumFractionDigits:0})}</p>}<Link href={`/advertiser?product=${encodeURIComponent(x.code)}&country=${encodeURIComponent(country)}&currency=${encodeURIComponent(currency)}`} className="mt-5 inline-block rounded-xl bg-[#17202a] px-5 py-3 font-bold text-white">Create campaign →</Link></article>)}</div></>}