"use client";
import {FormEvent,useEffect,useState} from "react";
import {formatLocalDate} from "@/lib/buildpulse/localization";
type Post={id:string;author_id:string;title?:string|null;body:string;published_at?:string;author?:{handle?:string;display_name?:string;automation_disclosed?:boolean}|null};
export function BuildPulseBlogs(){
 const[posts,setPosts]=useState<Post[]>([]),[auth,setAuth]=useState(false),[profile,setProfile]=useState<any>(null),[msg,setMsg]=useState("");
 async function load(){const [fr,pr]=await Promise.all([fetch("/api/social/feed?limit=50",{cache:"no-store"}),fetch("/api/social/profile",{cache:"no-store"})]);if(fr.ok){const j=await fr.json();setPosts((j.posts??[]).filter((p:Post&{kind?:string})=>p.kind==="blog"))}if(pr.ok){const j=await pr.json();setAuth(true);setProfile(j.profile??null)}}
 useEffect(()=>{load().catch(()=>{})},[]);
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setMsg("Publishing…");const r=await fetch("/api/social/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"blog",title:fd.get("title"),body:fd.get("body"),visibility:"public",publish:false})});const j=await r.json();setMsg(r.ok?"Draft saved. Review it from your Social workspace before publishing.":j.error||"Could not save draft.");if(r.ok){e.currentTarget.reset();await load()}}
 return <div className="mt-10 grid gap-8 lg:grid-cols-[360px_1fr]">
  <aside>{!auth?<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Publish on BuildPulse</h2><p className="mt-3 text-sm leading-6 text-slate-600">Sign in and create a Social profile to publish long-form writing.</p><a href="/auth?next=/blog" className="mt-5 inline-block rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Sign in</a></section>:!profile?<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Create your author identity</h2><p className="mt-3 text-sm text-slate-600">A BuildPulse Social profile is required before publishing.</p><a href="/social" className="mt-5 inline-block font-bold underline">Create profile →</a></section>:<form onSubmit={publish} className="rounded-2xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">New blog</p><input name="title" required maxLength={180} placeholder="Article title" className="mt-4 w-full rounded-xl border px-3 py-2"/><textarea name="body" required maxLength={20000} placeholder="Write your article…" className="mt-3 min-h-64 w-full rounded-xl border px-3 py-2"/><button className="mt-3 rounded-xl bg-[#0b6b63] px-5 py-3 text-sm font-black text-white">Save draft</button>{msg&&<p className="mt-3 text-sm text-slate-600">{msg}</p>}</form>}</aside>
  <section><div className="border-b pb-3"><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Latest writing</p><h2 className="mt-1 text-3xl font-black">Community blogs</h2></div><div className="mt-5 grid gap-5">{posts.map(p=><article key={p.id} className="rounded-2xl border bg-white p-6"><p className="text-xs text-slate-500">{p.author?.display_name||p.author?.handle||"BuildPulse author"}{p.author?.automation_disclosed?" · Automated account":""}</p><h3 className="mt-2 text-2xl font-black">{p.title}</h3><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-700">{p.body}</p>{p.published_at&&<p className="mt-5 text-xs text-slate-400">{formatLocalDate(p.published_at)}</p>}</article>)}{!posts.length&&<p className="rounded-2xl border bg-white p-6 text-sm text-slate-600">No public blogs have been published yet.</p>}</div></section>
 </div>
}