"use client";
import {useEffect,useState} from "react";
import {getBuildPulseLocale,getDeviceTimeZone} from "@/lib/buildpulse/localization";
type Story={id:string;title:string;summary?:string;category?:string;url:string;publishedAt?:string;translated:boolean;source:{name?:string;country?:string;region?:string;city?:string;language?:string}};
const countryFromLocale=(locale:string)=>{try{const l=new Intl.Locale(navigator.language);return l.region||""}catch{return""}};
export function BuildPulseLocalNews(){
 const [country,setCountry]=useState(""),[region,setRegion]=useState(""),[city,setCity]=useState(""),[stories,setStories]=useState<Story[]>([]),[state,setState]=useState("Detecting your local setup…"),[locale,setLocale]=useState("en"),[tz,setTz]=useState("UTC");
 useEffect(()=>{const l=getBuildPulseLocale(),t=getDeviceTimeZone();setLocale(l);setTz(t);try{const saved=JSON.parse(localStorage.getItem("buildpulse.local")||"{}");setCountry(saved.country||countryFromLocale(l));setRegion(saved.region||"");setCity(saved.city||"")}catch{setCountry(countryFromLocale(l))}},[]);
 useEffect(()=>{if(!country){setState("Choose a country to load local coverage.");return}const q=new URLSearchParams({country,locale});if(region)q.set("region",region);if(city)q.set("city",city);setState("Loading verified local coverage…");fetch("/api/buildpulse/local?"+q).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"failed");setStories(j.stories||[]);setState((j.stories||[]).length?"":"No verified local stories are available for this area yet.")}).catch(()=>setState("Local coverage is temporarily unavailable."))},[country,region,city,locale]);
 function save(){try{localStorage.setItem("buildpulse.local",JSON.stringify({country:country.toUpperCase(),region,city}))}catch{};setCountry(country.toUpperCase())}
 return <div className="grid gap-8 lg:grid-cols-[320px_1fr]"><aside className="h-fit rounded-2xl border border-black/10 bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Your local setup</p><p className="mt-2 text-sm text-slate-600">Language: {locale.toUpperCase()} · Time zone: {tz}</p><div className="mt-5 grid gap-3"><label className="text-xs font-bold">Country code<input value={country} onChange={e=>setCountry(e.target.value.slice(0,2).toUpperCase())} placeholder="GB" className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-xs font-bold">Region / state<input value={region} onChange={e=>setRegion(e.target.value)} placeholder="Optional" className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-xs font-bold">City<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Optional" className="mt-1 w-full rounded-lg border px-3 py-2"/></label><button onClick={save} className="rounded-lg bg-[#0b6b63] px-4 py-3 text-sm font-black text-white">Use this local edition</button></div><p className="mt-4 text-xs leading-5 text-slate-500">BuildPulse uses your browser language/time zone automatically. Exact city selection remains under your control; no precise-device-location permission is required.</p></aside><section><div className="mb-5 flex items-end justify-between border-b border-black/20 pb-3"><div><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Local</p><h2 className="mt-1 text-3xl font-black">{city||region||country||"Your area"}</h2></div><p className="text-xs text-slate-500">{stories.length} verified stories</p></div>{state&&<p className="mb-5 rounded-xl border bg-white p-4 text-sm text-slate-600">{state}</p>}<div className="grid gap-4">{stories.map(s=><article key={s.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex flex-wrap gap-2 text-[11px] font-black uppercase tracking-wide text-slate-500"><span>{s.source?.name||"Source"}</span>{s.source?.city&&<span>· {s.source.city}</span>}{s.translated&&<span className="text-[#0b6b63]">· translated</span>}</div><h3 className="mt-2 text-2xl font-black leading-tight"><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></h3>{s.summary&&<p className="mt-3 leading-7 text-slate-600">{s.summary}</p>}</article>)}</div></section></div>
}