type Campaign={name:string;eyebrow:string;copy:string;href:string;logo?:string;logoAlt?:string;cta:string;accent:string};
const campaigns:Campaign[]=[
{name:"ENTELΞKRON",eyebrow:"PRESALE · ECOSYSTEM ACCESS",copy:"Official token-sale information, eligibility, tokenomics and vesting disclosures.",href:"https://www.entelekron.io/",logo:"https://www.entelekron.io/email/logos/entelekron-logo-full-dark.png",logoAlt:"ENTELΞKRON",cta:"Explore presale",accent:"#7256d8"},
{name:"SOVRA Protocol",eyebrow:"SOVEREIGN PROTOCOL",copy:"Official SOVRA Protocol product, presale and ecosystem information.",href:"https://www.sovraprotocol.com/",logo:"https://www.sovraprotocol.com/assets/sovra_logo_4_64x64.png",logoAlt:"SOVRA Protocol",cta:"Explore SOVRA",accent:"#0b6b63"},
{name:"EnteleWALLET",eyebrow:"SECURE DIGITAL WALLET",copy:"Explore the official EnteleWALLET application and wallet platform.",href:"https://entelewallet.app/",cta:"Open wallet",accent:"#7058ff"},
{name:"EnteleEXCHANGE",eyebrow:"DIGITAL-ASSET EXCHANGE",copy:"Discover the EnteleEXCHANGE platform and official product information.",href:"https://enteleexchange.com/",logo:"https://enteleexchange.com/favicon.ico",logoAlt:"EnteleEXCHANGE",cta:"Explore exchange",accent:"#1268f3"},
{name:"TVK Wallet",eyebrow:"WHITE-LABEL WALLET",copy:"Buyer-branded wallet infrastructure for organizations building their own wallet product.",href:"https://tvkwallet.com/",logo:"https://tvkwallet.com/brand/tvk-wallet-wordmark-dark.svg",logoAlt:"TVK Wallet",cta:"View platform",accent:"#17202a"},
{name:"ENM · EnergieMIND",eyebrow:"ENERGY INTELLIGENCE",copy:"Explore EnergieMIND and the ENM ecosystem through its official network portal.",href:"https://enm.network/",cta:"Explore ENM",accent:"#00a86b"}];
const adSlots=[{name:"Your brand here",copy:"Homepage and edition placements for technology, finance and infrastructure brands."},{name:"Sponsor BuildPulse",copy:"Premium billboard, article and newsletter inventory is available now."}];
function Card({c}:{c:Campaign}){return <a href={c.href} target="_blank" rel="sponsored noopener noreferrer" className="group relative flex h-[230px] w-[310px] shrink-0 flex-col overflow-hidden rounded-2xl border border-black/10 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="absolute inset-x-0 top-0 h-2.5" style={{background:c.accent}}/>{c.logo?<div className="flex h-16 items-center"><img src={c.logo} alt={c.logoAlt||c.name} className="max-h-14 max-w-[235px] object-contain object-left" loading="lazy"/></div>:<div className="flex h-12 items-center text-xl font-black tracking-tight" style={{color:c.accent}}>{c.name}</div>}<p className="mt-3 text-[9px] font-black uppercase tracking-[.17em]" style={{color:c.accent}}>{c.eyebrow}</p><h3 className="mt-1 text-lg font-black">{c.name}</h3><p className="mt-2 flex-1 text-xs leading-5 text-[#53606b]">{c.copy}</p><span className="border-t border-black/10 pt-3 text-[10px] font-black uppercase tracking-[.12em]">{c.cta} →</span></a>}
export function BuildPulseHouseCampaigns(){const reel=[...campaigns,...campaigns];return <section className="overflow-hidden border-y border-[#17202a]/15 bg-[#eef2f0]" aria-label="Sponsored TVK ecosystem and advertising inventory"><div className="mx-auto max-w-[1440px] px-5 pt-9 md:px-10"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#65717c]">Sponsored · TVK ecosystem</p><h2 className="mt-2 text-2xl font-black tracking-tight">Platforms, infrastructure & ecosystem</h2></div><a href="/advertise" className="text-[10px] font-black uppercase tracking-[.16em] underline underline-offset-4">Advertise with BuildPulse</a></div></div><div className="mt-6 overflow-hidden pb-8"><div className="flex w-max gap-4 px-5 motion-safe:animate-[ticker_55s_linear_infinite] hover:[animation-play-state:paused] md:px-10">{reel.map((c,i)=><Card key={c.name+i} c={c}/>)}</div></div><div className="mx-auto grid max-w-[1440px] gap-4 px-5 pb-10 md:grid-cols-2 md:px-10">{adSlots.map(s=><a key={s.name} href="/advertise" className="flex min-h-32 items-center justify-between gap-5 rounded-2xl border-2 border-dashed border-[#17202a]/25 bg-white/55 p-6 transition hover:border-[#0b6b63]"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#0b6b63]">Advertising inventory</p><h3 className="mt-2 text-xl font-black">{s.name}</h3><p className="mt-2 max-w-xl text-sm text-[#53606b]">{s.copy}</p></div><span className="shrink-0 text-2xl">→</span></a>)}</div><div className="border-t border-black/10 bg-white/40"><p className="mx-auto max-w-[1440px] px-5 py-4 text-[10px] leading-5 text-[#65717c] md:px-10">Advertising disclosure: TVK ecosystem cards are first-party promotional placements and are separate from BuildPulse editorial coverage. Token-sale participation involves risk; review official eligibility, legal, vesting and risk disclosures. Commercial placements are labeled and remain subject to BuildPulse review.</p></div></section>}