type Campaign={name:string;eyebrow:string;copy:string;href:string;logo:string;logoAlt:string;cta:string};
const campaigns:Campaign[]=[
 {name:"ENTELΞKRON",eyebrow:"PRESALE · ECOSYSTEM ACCESS",copy:"Explore the official ENTELΞKRON token sale portal, round information, eligibility, tokenomics and vesting disclosures.",href:"https://www.entelekron.io/",logo:"https://www.entelekron.io/email/logos/entelekron-logo-full-dark.png",logoAlt:"ENTELΞKRON — The Sovereign Core of Civilization",cta:"Explore presale"},
 {name:"SOVRA Protocol",eyebrow:"PRESALE · ECOSYSTEM ACCESS",copy:"Review the official SOVRA Protocol presale schedule, eligibility, pricing, allocation, vesting and risk information.",href:"https://www.sovraprotocol.com/presale.html",logo:"https://www.sovraprotocol.com/assets/sovra_logo_4_64x64.png",logoAlt:"SOVRA Protocol",cta:"Explore presale"},
 {name:"EnteleEXCHANGE",eyebrow:"DIGITAL-ASSET EXCHANGE",copy:"Discover the EnteleEXCHANGE platform and its official product information.",href:"https://enteleexchange.com/",logo:"https://enteleexchange.com/favicon.ico",logoAlt:"EnteleEXCHANGE",cta:"Explore exchange"},
 {name:"TVK Wallet",eyebrow:"WHITE-LABEL WALLET PLATFORM",copy:"A buyer-branded wallet platform for organizations that want a serious wallet product under their own identity. Professional white-label packages start from USD 79,000.",href:"https://tvkwallet.com/",logo:"https://tvkwallet.com/brand/tvk-wallet-wordmark-dark.svg",logoAlt:"TVK Wallet Platform",cta:"View platform"}
];
export function BuildPulseHouseCampaigns(){
 return <section className="border-y border-[#17202a]/15 bg-[#eef2f0]" aria-label="Sponsored ecosystem campaigns"><div className="mx-auto max-w-[1440px] px-5 py-12 md:px-10"><div className="mb-6 flex items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#65717c]">Sponsored · TVK ecosystem</p><h2 className="mt-2 text-2xl font-black tracking-tight">Selected platforms & token sales</h2></div><span className="hidden text-[10px] font-bold uppercase tracking-[.16em] text-[#65717c] md:block">Promotional content</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{campaigns.map(c=><a key={c.name} href={c.href} target="_blank" rel="sponsored noopener noreferrer" className="group flex min-h-[290px] flex-col rounded-2xl border border-[#17202a]/15 bg-[#fbfaf6] p-6 transition hover:-translate-y-0.5 hover:border-[#0b6b63]/50 hover:shadow-lg"><div className="flex min-h-16 items-center"><img src={c.logo} alt={c.logoAlt} className="max-h-14 max-w-[240px] object-contain object-left" loading="lazy"/></div><p className="mt-6 text-[10px] font-black uppercase tracking-[.16em] text-[#0b6b63]">{c.eyebrow}</p><h3 className="mt-2 text-2xl font-black">{c.name}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[#53606b]">{c.copy}</p><span className="mt-5 border-t border-[#17202a]/15 pt-4 text-xs font-black uppercase tracking-[.1em]">{c.cta} →</span></a>)}</div><p className="mt-5 max-w-4xl text-[11px] leading-5 text-[#65717c]">Advertising disclosure: these are first-party promotional placements for TVK ecosystem projects. Token-sale participation involves risk; review the official eligibility, legal, vesting and risk disclosures before participating.</p></div></section>
}