"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@/utils/supabase/client";

type Product = { code:string; name:string; placement:string; width_px:number|null; height_px:number|null; max_copy_chars:number; price_usd:number|string; duration_days:number };
type Order = { id:string; headline:string|null; copy_text:string|null; destination_url:string; status:string; amount_usd:number|string; created_at:string };
type Metric={id:string;impressions:number;clicks:number;ctr:number};
type Quote={order_id:string;asset:string;network:string;expected_amount:number|string;destination:string;memo:string|null;expires_at:string;state:string;required_confirmations?:number};

export function BuildPulseAdvertiserPortal(){
  const search=useSearchParams();
  const supabase=useMemo(()=>createClient(),[]);
  const [userId,setUserId]=useState<string|null>(null);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [company,setCompany]=useState(""); const [billingEmail,setBillingEmail]=useState(""); const [website,setWebsite]=useState("");
  const [products,setProducts]=useState<Product[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [metrics,setMetrics]=useState<Record<string,Metric>>({}); const [quotes,setQuotes]=useState<Record<string,Quote>>({});
  const [product,setProduct]=useState(search.get("product")??""); const [headline,setHeadline]=useState(""); const [copy,setCopy]=useState(""); const [destination,setDestination]=useState("");
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);

  const selected=products.find(x=>x.code===product);
  async function refresh(uid?:string){
    const [{data:p,error:pError},{data:o,error:oError},{data:profile,error:profileError}]=await Promise.all([
      supabase.from("buildpulse_ad_products").select("code,name,placement,width_px,height_px,max_copy_chars,price_usd,duration_days").eq("active",true).order("price_usd"),
      supabase.from("buildpulse_ad_orders").select("id,headline,copy_text,destination_url,status,amount_usd,created_at").order("created_at",{ascending:false}).limit(50),
      supabase.from("buildpulse_advertiser_profiles").select("company_name,billing_email,website_url").maybeSingle()
    ]);
    if(pError||oError||profileError){setMessage((pError??oError??profileError)?.message??"Could not load advertiser data. Please try again.");if(uid)setUserId(uid);return;}
    setProducts((p??[]) as Product[]); setOrders((o??[]) as Order[]);
    if(profile){setCompany(profile.company_name??"");setBillingEmail(profile.billing_email??"");setWebsite(profile.website_url??"")}
    if(!product&&p?.[0])setProduct(p[0].code);
    if(uid){setUserId(uid);const {data:q}=await supabase.from("buildpulse_ad_payment_quotes").select("order_id,asset,network,expected_amount,destination,memo,expires_at,state,required_confirmations").in("state",["open","observed"]).order("created_at",{ascending:false});if(q)setQuotes(Object.fromEntries((q as Quote[]).map(item=>[item.order_id,item])));const report=await fetch("/api/buildpulse/advertiser/report",{credentials:"include"}).then(r=>r.ok?r.json():null).catch(()=>null);if(report?.campaigns)setMetrics(Object.fromEntries((report.campaigns as Metric[]).map(item=>[item.id,item]))) }
  }
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUserId(data.user?.id??null);void refresh(data.user?.id)});const {data:s}=supabase.auth.onAuthStateChange((_e,session)=>{setUserId(session?.user?.id??null);void refresh(session?.user?.id)});return()=>s.subscription.unsubscribe()},[]);

  async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:"Signed in.");setBusy(false)}
  async function signUp(){setBusy(true);setMessage("");const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/advertiser`}});setMessage(error?error.message:"Account created. Check your email if confirmation is required.");setBusy(false)}
  async function saveProfile(e:FormEvent){e.preventDefault();if(!userId)return;setBusy(true);setMessage("");try{const response=await fetch("/api/buildpulse/advertiser/profile",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyName:company,billingEmail,websiteUrl:website})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Advertiser profile could not be saved");setMessage("Advertiser profile saved.")}catch(error){setMessage(error instanceof Error?error.message:"Advertiser profile could not be saved")}finally{setBusy(false)}}
  async function createOrder(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const response=await fetch("/api/buildpulse/advertiser/orders",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({productCode:product,headline,copyText:copy,destinationUrl:destination})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Campaign draft could not be created");setMessage(`Draft campaign created: ${body.order?.id??""}`);setHeadline("");setCopy("");setDestination("");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Campaign draft could not be created")}finally{setBusy(false)}}
  async function uploadCreative(orderId:string,file:File|null){if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("orderId",orderId);form.set("file",file);const response=await fetch("/api/buildpulse/advertiser/creative",{method:"POST",credentials:"include",body:form});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Creative upload failed");setMessage("Creative uploaded and queued for review.")}catch(error){setMessage(error instanceof Error?error.message:"Creative upload failed")}finally{setBusy(false)}}

  if(!userId)return <section className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Advertiser account</h2><p className="mt-2 text-slate-600">Sign in or create an account to prepare campaigns. Payment never causes automatic publication.</p><form onSubmit={signIn} className="mt-6 grid gap-3"><input className="rounded-xl border px-4 py-3" type="email" required placeholder="Business email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="rounded-xl border px-4 py-3" type="password" required minLength={8} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="flex gap-3"><button disabled={busy} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Sign in</button><button disabled={busy} type="button" onClick={signUp} className="rounded-xl border px-5 py-3 font-bold">Create account</button></div></form>{message&&<p className="mt-4 text-sm text-slate-600">{message}</p>}</section>;

  return <div className="grid gap-8">
    <section className="rounded-3xl border bg-white p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Advertiser profile</h2><p className="mt-1 text-sm text-slate-500">Billing and company identity.</p></div><button onClick={()=>supabase.auth.signOut()} className="text-sm font-bold underline">Sign out</button></div><form onSubmit={saveProfile} className="mt-6 grid gap-3 md:grid-cols-2"><input className="rounded-xl border px-4 py-3" placeholder="Company name" value={company} onChange={e=>setCompany(e.target.value)}/><input className="rounded-xl border px-4 py-3" type="email" placeholder="Billing email" value={billingEmail} onChange={e=>setBillingEmail(e.target.value)}/><input className="rounded-xl border px-4 py-3 md:col-span-2" type="url" placeholder="https://company.example" value={website} onChange={e=>setWebsite(e.target.value)}/><button disabled={busy} className="w-fit rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Save profile</button></form></section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-black">Create campaign draft</h2><p className="mt-2 text-sm text-slate-600">Price, duration and copy limits are enforced server-side from the selected inventory product.</p><form onSubmit={createOrder} className="mt-6 grid gap-4"><select required className="rounded-xl border px-4 py-3" value={product} onChange={e=>setProduct(e.target.value)}>{products.map(x=><option key={x.code} value={x.code}>{x.name} — USD {Number(x.price_usd).toLocaleString("en-US")} / {x.duration_days}d</option>)}</select>{selected&&<p className="text-xs font-bold uppercase tracking-wider text-slate-500">{selected.width_px&&selected.height_px?`${selected.width_px} × ${selected.height_px}px · `:""}maximum {selected.max_copy_chars} characters</p>}<input className="rounded-xl border px-4 py-3" maxLength={120} placeholder="Campaign headline" value={headline} onChange={e=>setHeadline(e.target.value)}/><textarea required className="min-h-32 rounded-xl border px-4 py-3" maxLength={selected?.max_copy_chars??300} placeholder="Sponsor copy" value={copy} onChange={e=>setCopy(e.target.value)}/><div className="text-right text-xs text-slate-500">{copy.length}/{selected?.max_copy_chars??300}</div><input required className="rounded-xl border px-4 py-3" type="url" pattern="https://.*" placeholder="https://destination.example" value={destination} onChange={e=>setDestination(e.target.value)}/><button disabled={busy||!product} className="w-fit rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Create draft</button></form>{message&&<p className="mt-4 text-sm text-slate-600">{message}</p>}</section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-black">Campaigns</h2><div className="mt-5 grid gap-3">{orders.map(o=><article key={o.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><strong>{o.headline||"Untitled campaign"}</strong><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase">{o.status}</span></div><p className="mt-2 text-sm text-slate-600">{o.copy_text}</p><p className="mt-2 text-xs text-slate-500">USD {Number(o.amount_usd).toLocaleString("en-US")} · {new Date(o.created_at).toLocaleString()}</p>{quotes[o.id]&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs"><p className="font-bold">Crypto invoice · {quotes[o.id].state}</p><p className="mt-1">Send exactly <span className="font-mono font-bold">{String(quotes[o.id].expected_amount)} {quotes[o.id].asset}</span> on {quotes[o.id].network}</p><p className="mt-1 break-all font-mono">{quotes[o.id].destination}</p>{quotes[o.id].memo&&<p className="mt-1">Memo/tag: <span className="font-mono">{quotes[o.id].memo}</span></p>}<p className="mt-1 text-slate-500">Requires {quotes[o.id].required_confirmations??1} network confirmation{(quotes[o.id].required_confirmations??1)===1?"":"s"} · quote expires {new Date(quotes[o.id].expires_at).toLocaleString()}</p></div>}{metrics[o.id]&&<p className="mt-2 text-xs font-semibold text-slate-600">{metrics[o.id].impressions.toLocaleString()} verified impressions · {metrics[o.id].clicks.toLocaleString()} verified clicks · {metrics[o.id].ctr}% CTR</p>}{["draft","awaiting_payment","payment_detected","review"].includes(o.status)&&<label className="mt-3 inline-flex cursor-pointer rounded-xl border px-3 py-2 text-xs font-bold">Upload PNG/JPEG/WebP creative<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void uploadCreative(o.id,e.target.files?.[0]??null)}/></label>}</article>)}{orders.length===0&&<p className="text-slate-500">No campaigns yet.</p>}</div></section>
  </div>
}
