"use client";import {FormEvent,useEffect,useState} from "react";
type Comment={id:string;body:string;created_at:string;author?:{handle?:string;display_name?:string;automation_disclosed?:boolean}|null};
export function BuildPulseSocialInteractions({postId,authorId,canInteract}:{postId:string;authorId:string;canInteract:boolean}){const[counts,setCounts]=useState<Record<string,number>>({like:0,insightful:0,support:0}),[comments,setComments]=useState<Comment[]>([]),[following,setFollowing]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/social/interactions?postId="+encodeURIComponent(postId),{cache:"no-store"});if(r.ok){const j=await r.json();setCounts(j.reactions||counts);setComments(j.comments||[])}}
 useEffect(()=>{load().catch(()=>{})},[postId]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!canInteract){setMsg("Sign in to interact.");return null}setBusy(true);setMsg("");try{const r=await fetch("/api/social/interactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...extra})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Action failed");await load();return j}catch(e){setMsg(e instanceof Error?e.message:"Action failed");return null}finally{setBusy(false)}}
 async function react(reaction:string){await act("react",{postId,reaction})}
 async function follow(){const j=await act(following?"unfollow":"follow",{targetUserId:authorId});if(j)setFollowing(!following)} async function safety(action:"mute"|"block"|"report"){if(!canInteract){setMsg("Sign in to use safety controls.");return}const reason=action==="report"?"Reported from feed by the signed-in reader.":"";setBusy(true);try{const r=await fetch("/api/social/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,targetUserId:authorId,targetPostId:action==="report"?postId:undefined,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Safety action failed");setMsg(action==="report"?"Report submitted for review.":action==="mute"?"Author muted. Refreshing feed will hide their posts.":"Author blocked. Refreshing feed will hide their posts.")}catch(e){setMsg(e instanceof Error?e.message:"Safety action failed")}finally{setBusy(false)}}
 async function comment(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),body=String(fd.get("body")||"");const j=await act("comment",{postId,body});if(j)e.currentTarget.reset()}
 return <div className="mt-5 border-t border-black/10 pt-4"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>react("like")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Like {counts.like||0}</button><button disabled={busy} onClick={()=>react("insightful")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Insightful {counts.insightful||0}</button><button disabled={busy} onClick={()=>react("support")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Support {counts.support||0}</button>{canInteract&&<button disabled={busy} onClick={follow} className="rounded-full border px-3 py-1.5 text-xs font-bold">{following?"Following":"Follow author"}</button>}{canInteract&&<button disabled={busy} onClick={()=>safety("mute")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Mute</button>}{canInteract&&<button disabled={busy} onClick={()=>safety("report")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Report</button>}{canInteract&&<button disabled={busy} onClick={()=>safety("block")} className="rounded-full border px-3 py-1.5 text-xs font-bold">Block</button>}</div>{msg&&<p className="mt-2 text-xs text-slate-500">{msg}</p>}<div className="mt-4 space-y-2">{comments.slice(-6).map(c=><div key={c.id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="text-xs font-bold text-slate-500">{c.author?.display_name||c.author?.handle||"Member"}{c.author?.automation_disclosed?" · automated":""}</p><p className="mt-1 whitespace-pre-wrap">{c.body}</p></div>)}</div>{canInteract?<form onSubmit={comment} className="mt-3 flex gap-2"><input name="body" required maxLength={2000} placeholder="Add a comment" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><button disabled={busy} className="rounded-lg bg-slate-950 px-4 py-2 text-xs font-black text-white">Comment</button></form>:<p className="mt-3 text-xs text-slate-500">Sign in to react, follow or comment.</p>}</div>}