"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type M={role:"user"|"assistant";content:string};
export function BuildPulseSovraGuide(){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<M[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const end=useRef<HTMLDivElement>(null);
 useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages,busy]);
 async function send(e:FormEvent){e.preventDefault();const q=input.trim();if(!q||busy)return;const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setInput("");setBusy(true);setError("");try{const r=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||"SOVRA request failed");setMessages(v=>[...v,{role:"assistant",content:d.content}])}catch(x){setError(x instanceof Error?x.message:"SOVRA is temporarily unavailable.")}finally{setBusy(false)}}
 return <div className="fixed bottom-4 left-4 z-[85]">
  {open&&<div className="mb-3 flex h-[min(560px,70vh)] w-[min(390px,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-black/15 bg-[#fbfaf6] shadow-2xl">
   <header className="flex items-center justify-between border-b border-black/10 bg-[#123c3a] px-4 py-3 text-white"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/60">SOVRA AI</p><h2 className="text-base font-black">BuildPulse guide</h2></div><button onClick={()=>setOpen(false)} aria-label="Close SOVRA AI guide" className="rounded-full border border-white/25 px-3 py-1 text-xs font-black">Close</button></header>
   <div className="flex-1 overflow-y-auto p-4">{messages.length===0?<div><p className="text-lg font-black">How can I help?</p><p className="mt-2 text-sm leading-6 text-slate-600">Ask about BuildPulse, technology, research, writing, planning or the TVK ecosystem.</p><div className="mt-4 grid gap-2">{["What is BuildPulse?","Show me today’s intelligence","Explain the SOVRA ecosystem"].map(x=><button key={x} onClick={()=>setInput(x)} className="rounded-lg border bg-white p-3 text-left text-xs font-bold">{x} →</button>)}</div></div>:<div className="space-y-3">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-auto max-w-[85%] rounded-xl bg-[#17202a] px-3 py-2 text-xs leading-5 text-white":"max-w-[92%] rounded-xl bg-[#eef4f1] px-3 py-2 text-xs leading-5 whitespace-pre-wrap"}>{m.content}</div>)}{busy&&<p className="text-xs font-bold text-[#0b6b63]">Thinking…</p>}<div ref={end}/></div>}{error&&<p className="mt-3 text-xs font-bold text-red-700">{error}</p>}</div>
   <form onSubmit={send} className="flex gap-2 border-t border-black/10 p-3"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask SOVRA…" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm outline-none focus:border-[#0b6b63]"/><button disabled={busy||!input.trim()} className="rounded-lg bg-[#0b6b63] px-4 text-xs font-black text-white disabled:opacity-40">Send</button></form>
  </div>}
  <button onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open SOVRA AI guide" className={"group flex items-end gap-2 transition-all duration-300 "+(open?"scale-110":"hover:scale-110")}>
   <span className={"relative block origin-bottom transition-all duration-300 "+(open?"h-28 w-16":"h-20 w-11")}><span className="absolute left-1/2 top-0 h-5 w-5 -translate-x-1/2 rounded-full bg-[#17202a]"/><span className="absolute left-1/2 top-5 h-10 w-5 -translate-x-1/2 rounded-t-full bg-[#17202a]"/><span className="absolute left-[12px] top-7 h-9 w-1 origin-top rotate-[10deg] bg-[#17202a]"/><span className="absolute right-[12px] top-7 h-9 w-1 origin-top -rotate-[10deg] bg-[#17202a]"/><span className="absolute bottom-0 left-[16px] h-8 w-1 bg-[#17202a]"/><span className="absolute bottom-0 right-[16px] h-8 w-1 bg-[#17202a]"/></span>
   <span className="rounded-lg border border-black/15 bg-[#fbfaf6]/95 px-3 py-2 text-left shadow-lg"><span className="block text-[9px] font-black uppercase tracking-[.16em] text-[#0b6b63]">SOVRA AI</span><span className="block text-[11px] font-black">{open?"Guide open":"Ask the guide"}</span></span>
  </button>
 </div>
}