"use client";
import {FormEvent,useEffect,useState} from "react";
type Profile={handle:string;display_name?:string;bio?:string;discoverable:boolean;allow_messages:string;account_type?:string;automation_disclosed?:boolean;verified_kind?:string|null};
type FeedPost={id:string;kind:string;title?:string|null;body:string;published_at?:string;author?:{handle?:string;display_name?:string;account_type?:string;automation_disclosed?:boolean;verified_kind?:string|null}|null};
export function BuildPulseSocialApp(){
 const [profile,setProfile]=useState<Profile|null>(null),[auth,setAuth]=useState<"loading"|"yes"|"no">("loading"),[feed,setFeed]=useState<FeedPost[]>([]),[message,setMessage]=useState("");
 async function load(){const [pr,fr]=await Promise.all([fetch("/api/social/profile",{cache:"no-store"}),fetch("/api/social/feed?limit=30",{cache:"no-store"})]);if(pr.ok){const j=await pr.json();setAuth("yes");setProfile(j.profile??null)}else setAuth("no");if(fr.ok){const j=await fr.json();setFeed(j.posts??[])}}
 useEffect(()=>{load().catch(()=>setAuth("no"))},[]);
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setMessage("Saving profile…");const r=await fetch("/api/social/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle:fd.get("handle"),displayName:fd.get("displayName"),bio:fd.get("bio"),allowMessages:fd.get("allowMessages"),discoverable:fd.get("discoverable")==="yes"})});const j=await r.json();setMessage(r.ok?"Profile saved.":j.error||"Could not save profile.");if(r.ok)setProfile(j.profile)}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setMessage("Publishing…");const r=await fetch("/api/social/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:fd.get("kind"),title:fd.get("title"),body:fd.get("body"),visibility:fd.get("visibility"),publish:true})});const j=await r.json();setMessage(r.ok?"Published.":j.error||"Could not publish.");if(r.ok){e.currentTarget.reset();await load()}}
 return <div className="grid gap-8 xl:grid-cols-[360px_1fr]"><aside className="space-y-5">{auth==="no"?<div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Sign in to participate</h2><p className="mt-2 text-sm leading-6 text-slate-600">Public posts can be read without an account. Publishing and profile controls require authentication.</p><a href="/auth?next=/social" className="mt-4 inline-block rounded-lg bg-[#0b6b63] px-4 py-3 text-sm font-black text-white">Sign in</a></div>:auth==="yes"?<form onSubmit={saveProfile} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Profile</p><h2 className="mt-1 text-xl font-black">{profile?"Edit profile":"Create your Social identity"}</h2><div className="mt-4 grid gap-3"><input name="handle" required pattern="[A-Za-z0-9_]{3,30}" defaultValue={profile?.handle||""} placeholder="Unique handle" className="rounded-lg border px-3 py-2"/><input name="displayName" defaultValue={profile?.display_name||""} placeholder="Display name" className="rounded-lg border px-3 py-2"/><textarea name="bio" maxLength={500} defaultValue={profile?.bio||""} placeholder="Bio" className="min-h-24 rounded-lg border px-3 py-2"/><select name="allowMessages" defaultValue={profile?.allow_messages||"followers"} className="rounded-lg border px-3 py-2"><option value="nobody">Messages: nobody</option><option value="followers">Messages: followers</option><option value="everyone">Messages: everyone</option></select><label className="text-sm"><input type="checkbox" name="discoverable" value="yes" defaultChecked={profile?.discoverable??true} className="mr-2"/>Discoverable profile</label><button className="rounded-lg bg-slate-950 px-4 py-3 text-sm font-black text-white">Save profile</button></div></form>:<div className="rounded-2xl border bg-white p-5 text-sm">Loading account…</div>}
 {auth==="yes"&&profile?<form onSubmit={publish} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Publish</p><div className="mt-4 grid gap-3"><select name="kind" className="rounded-lg border px-3 py-2"><option value="post">Post</option><option value="blog">Blog</option></select><input name="title" maxLength={180} placeholder="Blog title (required for blogs)" className="rounded-lg border px-3 py-2"/><textarea name="body" required maxLength={20000} placeholder="Write something…" className="min-h-36 rounded-lg border px-3 py-2"/><select name="visibility" className="rounded-lg border px-3 py-2"><option value="public">Public</option><option value="followers">Followers</option><option value="private">Private</option></select><button className="rounded-lg bg-[#0b6b63] px-4 py-3 text-sm font-black text-white">Publish</button></div></form>:null}{message&&<p className="rounded-xl border bg-white p-3 text-sm text-slate-600">{message}</p>}</aside>
 <section><div className="mb-5 flex items-end justify-between border-b border-black/20 pb-3"><div><p className="text-xs font-black uppercase tracking-widest text-[#0b6b63]">Social feed</p><h2 className="mt-1 text-3xl font-black">Public conversation</h2></div><span className="text-xs text-slate-500">{feed.length} recent posts</span></div><div className="grid gap-4">{feed.map(p=><article key={p.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><strong className="text-slate-900">{p.author?.display_name||p.author?.handle||"BuildPulse member"}</strong>{p.author?.handle&&<span>@{p.author.handle}</span>}{p.author?.automation_disclosed&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase">Automated account</span>}{p.author?.verified_kind&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black uppercase text-emerald-800">{p.author.verified_kind}</span>}</div>{p.title&&<h3 className="mt-3 text-2xl font-black">{p.title}</h3>}<p className="mt-3 whitespace-pre-wrap leading-7 text-slate-700">{p.body}</p><p className="mt-4 text-[11px] uppercase tracking-wide text-slate-400">{p.kind}{p.published_at?" · "+new Date(p.published_at).toLocaleString():""}</p></article>)}{!feed.length&&<div className="rounded-2xl border bg-white p-6 text-sm text-slate-600">No public posts have been published yet.</div>}</div></section></div>
}