"use client";
import {FormEvent,useEffect,useState} from "react";
type C={id:string;kind:"direct"|"group"|"channel";title?:string|null;members:Array<{user_id:string;role:string;profile?:{handle?:string;display_name?:string;automation_disclosed?:boolean}|null}>};
export function SocialConversations(){
 const [items,setItems]=useState<C[]>([]),[status,setStatus]=useState("");
 async function load(){const r=await fetch("/api/social/conversations",{cache:"no-store"});const j=await r.json();if(r.ok)setItems(j.conversations??[]);else setStatus(j.error||"Conversations unavailable.")}
 useEffect(()=>{load().catch(()=>setStatus("Conversations unavailable."))},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),kind=String(fd.get("kind")),handles=String(fd.get("handles")||"").split(",").map(x=>x.trim().replace(/^@/,"")).filter(Boolean);setStatus("Creating…");const r=await fetch("/api/social/conversations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,title:fd.get("title"),handles})});const j=await r.json();setStatus(r.ok?"Conversation created. Encrypted message sending remains disabled until the audited E2EE client is released.":j.error||"Could not create conversation.");if(r.ok){e.currentTarget.reset();await load()}}
 return <section className="mt-8 rounded-3xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Conversations</p><h2 className="mt-1 text-2xl font-black">Direct, group & channel setup</h2><p className="mt-2 text-sm leading-6 text-slate-600">Conversation membership is live. Message storage is ciphertext-only; BuildPulse will not offer plaintext messaging until an audited end-to-end encryption protocol is integrated.</p><form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-2"><select name="kind" className="rounded-lg border p-3"><option value="direct">Direct</option><option value="group">Group</option><option value="channel">Channel</option></select><input name="title" maxLength={120} placeholder="Group/channel title" className="rounded-lg border p-3"/><input name="handles" required placeholder="Member handle(s), comma separated" className="rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-[#17202a] px-4 py-3 text-sm font-black text-white md:col-span-2">Create conversation</button></form>{status&&<p role="status" className="mt-3 text-sm font-bold text-slate-600">{status}</p>}<div className="mt-5 grid gap-3">{items.map(c=><article key={c.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{c.title||"Direct conversation"}</strong><span className="text-[10px] font-black uppercase text-slate-400">{c.kind}</span></div><p className="mt-2 text-xs text-slate-500">{c.members.map(m=>m.profile?.handle?"@"+m.profile.handle+(m.profile.automation_disclosed?" [automated]":""):"Member").join(" · ")}</p></article>)}{!items.length&&<p className="text-sm text-slate-500">No conversations yet.</p>}</div></section>
}