"use client";
import {FormEvent,useEffect,useRef,useState} from "react";\ntype SpeechRecognitionCtor=new()=>any;
import {usePathname} from "next/navigation";
import {getBuildPulseLocale} from "@/lib/buildpulse/localization";
type Msg={role:"user"|"assistant";content:string}; type Prefs={voice:boolean;motion:boolean}; type Profile={name:string};
const copy:Record<string,string[]>={en:["SOVRA AI guide","Your adaptive BuildPulse guide.","Hide","Show SOVRA","Ask me anything…","Send","Voice","Motion","AI assistant · not a human"],tr:["SOVRA AI rehberi","Uyarlanabilir BuildPulse rehberiniz.","Gizle","SOVRA'yı göster","Bana sorun…","Gönder","Ses","Animasyon","AI asistanı · insan değildir"],de:["SOVRA AI-Hilfe","Ihre adaptive BuildPulse-Hilfe.","Ausblenden","SOVRA zeigen","Fragen Sie mich…","Senden","Stimme","Animation","KI-Assistent · kein Mensch"]};
export function SovraPageGuide(){
 const path=usePathname(),[open,setOpen]=useState(false),[hidden,setHidden]=useState(false),[lang,setLang]=useState("en"),[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[prefs,setPrefs]=useState<Prefs>({voice:false,motion:true}),[profile,setProfile]=useState<Profile>({name:""}),[nameInput,setNameInput]=useState(""),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[micError,setMicError]=useState(""),end=useRef<HTMLDivElement>(null),recognition=useRef<any>(null);
 useEffect(()=>{setLang(getBuildPulseLocale());const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;try{const p=localStorage.getItem("bp_sovra_prefs");if(p)setPrefs(JSON.parse(p));else if(reduced)setPrefs(v=>({...v,motion:false}));const pr=localStorage.getItem("bp_sovra_profile");if(pr){const parsed=JSON.parse(pr);if(typeof parsed?.name==="string")setProfile({name:parsed.name.slice(0,80)})}}catch{if(reduced)setPrefs(v=>({...v,motion:false}))}},[]);
 useEffect(()=>end.current?.scrollIntoView({behavior:prefs.motion?"smooth":"auto"}),[messages,busy,prefs.motion]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==="Escape")setOpen(false)}document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[]);
 useEffect(()=>()=>{if("speechSynthesis"in window)window.speechSynthesis.cancel();recognition.current?.abort?.()},[]);
 function save(next:Prefs){setPrefs(next);try{localStorage.setItem("bp_sovra_prefs",JSON.stringify(next))}catch{}}
 function speak(text:string,force=false){if((!prefs.voice&&!force)||!("speechSynthesis"in window))return;const synth=window.speechSynthesis;synth.cancel();setOpen(true);setSpeaking(true);const langCode=lang==="tr"?"tr-TR":lang==="de"?"de-DE":"en-US",voices=synth.getVoices(),base=langCode.split("-")[0],voice=voices.find(v=>v.lang===langCode&&/female|samantha|zira|ava|susan|karen|victoria/i.test(v.name))||voices.find(v=>v.lang.startsWith(base))||voices[0],chunks=(text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text]).map(x=>x.trim()).filter(Boolean).slice(0,12);if(!chunks.length){setSpeaking(false);return}synth.resume();chunks.forEach((chunk,i)=>{const part=new SpeechSynthesisUtterance(chunk);part.lang=langCode;part.rate=.96;part.pitch=1.03;if(voice)part.voice=voice;if(i===chunks.length-1){part.onend=()=>setSpeaking(false);part.onerror=()=>setSpeaking(false)}synth.speak(part)})}\n async function startListening(){if(listening){recognition.current?.stop?.();return}setMicError("");try{await navigator.mediaDevices?.getUserMedia?.({audio:true})}catch{setMicError("Microphone permission is required.");return}const speechWindow=window as typeof window & {SpeechRecognition?:SpeechRecognitionCtor;webkitSpeechRecognition?:SpeechRecognitionCtor};const R=speechWindow.SpeechRecognition||speechWindow.webkitSpeechRecognition;if(!R){setMicError("Voice input is not supported by this browser.");return}const r=new R();recognition.current=r;r.lang=lang==="tr"?"tr-TR":lang==="de"?"de-DE":"en-US";r.interimResults=true;r.continuous=false;r.onstart=()=>{setListening(true);setOpen(true)};r.onresult=(ev:any)=>{let text="";for(let i=ev.resultIndex;i<ev.results.length;i++)text+=ev.results[i][0].transcript;setInput(text.trim())};r.onerror=(ev:any)=>{setListening(false);setMicError(ev.error==="not-allowed"?"Microphone permission was denied.":"I could not hear that clearly. Please try again.")};r.onend=()=>setListening(false);r.start()}}