"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import {getBuildPulseLocale} from "@/lib/buildpulse/localization";
type Msg={role:"user"|"assistant";content:string}; type Prefs={voice:boolean;motion:boolean};
const copy:Record<string,string[]>={en:["SOVRA AI guide","Your adaptive BuildPulse guide.","Hide","Show SOVRA","Ask me anything…","Send","Voice","Motion","AI assistant · not a human"],tr:["SOVRA AI rehberi","Uyarlanabilir BuildPulse rehberiniz.","Gizle","SOVRA'yı göster","Bana sorun…","Gönder","Ses","Animasyon","AI asistanı · insan değildir"],de:["SOVRA AI-Hilfe","Ihre adaptive BuildPulse-Hilfe.","Ausblenden","SOVRA zeigen","Fragen Sie mich…","Senden","Stimme","Animation","KI-Assistent · kein Mensch"]};
export function SovraPageGuide(){
 const path=usePathname(),[open,setOpen]=useState(false),[hidden,setHidden]=useState(false),[lang,setLang]=useState("en"),[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[prefs,setPrefs]=useState<Prefs>({voice:false,motion:true}),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setLang(getBuildPulseLocale());try{const p=localStorage.getItem("bp_sovra_prefs");if(p)setPrefs(JSON.parse(p))}catch{}},[]);
 useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages,busy]);
 function save(next:Prefs){setPrefs(next);try{localStorage.setItem("bp_sovra_prefs",JSON.stringify(next))}catch{}}
 function speak(text:string){if(!prefs.voice||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,1200));u.lang=lang==="tr"?"tr-TR":lang==="de"?"de-DE":"en-US";window.speechSynthesis.speak(u)}
 async function send(e:FormEvent){e.preventDefault();const q=input.trim();if(!q||busy)return;const context:Msg={role:"user",content:`[Current BuildPulse page: ${path}] ${q}`},next=[...messages,context];setMessages(v=>[...v,{role:"user",content:q}]);setInput("");setBusy(true);try{const r=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next})});const d=await r.json();const a=r.ok?d.content:(d.error||"I am temporarily unavailable.");setMessages(v=>[...v,{role:"assistant",content:a}]);if(r.ok)speak(a)}catch{setMessages(v=>[...v,{role:"assistant",content:"I am temporarily unavailable."}])}finally{setBusy(false)}}
 const t=copy[lang]||copy.en;
 if(hidden)return <button onClick={()=>setHidden(false)} className="fixed bottom-4 left-4 z-[85] rounded-full border border-[#8ab4ad] bg-[#eef7f5] px-4 py-2 text-xs font-black shadow-lg">{t[3]}</button>;
 return <aside aria-label={t[0]} className="fixed bottom-4 left-4 z-[85] max-w-[calc(100vw-32px)]">
  {open&&<section className="mb-3 flex h-[min(540px,68vh)] w-[min(390px,calc(100vw-32px))] flex-col overflow-hidden rounded-2xl border border-[#8ab4ad] bg-[#fbfaf6]/98 shadow-2xl backdrop-blur">
   <header className="flex items-center justify-between bg-[#123c3a] px-4 py-3 text-white"><div><b className="text-sm">{t[0]}</b><p className="text-[10px] text-white/65">{t[8]}</p></div><button onClick={()=>setOpen(false)} className="rounded-full border border-white/25 px-3 py-1 text-xs">×</button></header>
   <div className="flex-1 overflow-y-auto p-4">{messages.length===0?<><h3 className="text-xl font-black">Hello. I’m SOVRA.</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t[1]} I can use the page you are viewing as context and help you navigate, understand, write and explore.</p><div className="mt-4 flex flex-wrap gap-2">{["Explain this page","What can I do here?","Open Build with AI"].map(x=><button key={x} onClick={()=>setInput(x)} className="rounded-full border px-3 py-2 text-xs font-bold">{x}</button>)}</div></>:<div className="space-y-3">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-auto max-w-[85%] rounded-xl bg-[#17202a] px-3 py-2 text-xs leading-5 text-white":"max-w-[92%] rounded-xl bg-[#eef7f5] px-3 py-2 text-xs leading-5 whitespace-pre-wrap"}>{m.content}</div>)}{busy&&<p className="text-xs font-bold text-[#0b6b63]">SOVRA is thinking…</p>}<div ref={end}/></div>}</div>
   <div className="flex items-center gap-2 border-t px-3 py-2 text-[10px] font-bold"><button onClick={()=>save({...prefs,voice:!prefs.voice})} aria-pressed={prefs.voice} className="rounded-full border px-2 py-1">{t[6]} {prefs.voice?"ON":"OFF"}</button><button onClick={()=>save({...prefs,motion:!prefs.motion})} aria-pressed={prefs.motion} className="rounded-full border px-2 py-1">{t[7]} {prefs.motion?"ON":"OFF"}</button><span className="ml-auto text-slate-500">Preferences stay on this device</span></div>
   <form onSubmit={send} className="flex gap-2 border-t p-3"><input value={input} onChange={e=>setInput(e.target.value)} placeholder={t[4]} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-sm outline-none focus:border-[#0b6b63]"/><button disabled={!input.trim()||busy} className="rounded-xl bg-[#123c3a] px-4 text-xs font-black text-white disabled:opacity-40">{t[5]}</button></form>
  </section>}
  <div className="flex items-end gap-2"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="group relative block origin-bottom"><img src="https://sovraprotocol.com/assets/sovra-guide.webp" alt="SOVRA AI guide" width="128" height="194" className={`object-contain drop-shadow-xl transition-all duration-500 ${open?"h-[190px] w-[128px]":"h-[145px] w-[96px] group-hover:scale-110"} ${prefs.motion?"animate-[pulse_5s_ease-in-out_infinite]":""}`}/><span className={`absolute right-0 top-8 h-3 w-3 rounded-full bg-[#35c58b] shadow-[0_0_16px_rgba(53,197,139,.9)] ${prefs.motion?"animate-ping":""}`}/></button>
   <div className="mb-1 rounded-xl border border-[#8ab4ad] bg-[#eef7f5]/95 p-3 text-[#123c3a] shadow-xl"><button onClick={()=>setOpen(v=>!v)} className="text-left"><strong className="block text-xs">{t[0]}</strong><span className="block text-[10px]">{open?"Listening and ready":t[1]}</span></button><button onClick={()=>setHidden(true)} className="mt-2 text-[10px] font-bold underline">{t[2]}</button></div>
  </div>
 </aside>
}