"use client";
import {useEffect,useState} from "react";
type Rail={asset:string;network:string};type Props={planCode:string;interval:"month"|"year"};
export default function SubscriptionCryptoOptions({planCode,interval}:Props){
 const[rails,setRails]=useState<Rail[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[paymentId,setPaymentId]=useState(""),[tx,setTx]=useState("");
 useEffect(()=>{(async()=>{try{const {createClient}=await import("@/utils/supabase/client");const sb=createClient();const {data}=await sb.functions.invoke("buildpulse-payment",{body:{action:"capabilities"}});if(data?.ok&&Array.isArray(data.rails))setRails(data.rails)}catch{}})()},[]);
 async function quote(r:Rail){setBusy(true);setMsg("Creating a verified 30-minute crypto quote…");try{const {createClient}=await import("@/utils/supabase/client");const sb=createClient();const {data,error}=await sb.functions.invoke("buildpulse-payment",{body:{action:"subscription_quote",planCode,billingInterval:interval,asset:r.asset,network:r.network}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||"quote_failed");const p=data.payment;setPaymentId(p.id);setMsg(`Send exactly ${p.expected_amount} ${p.asset} on ${p.network} to ${p.destination}${p.memo?` · destination tag/memo ${p.memo}`:""}. This prepaid ${interval==="year"?"annual":"monthly"} term activates only after on-chain verification. Quote expires ${new Date(p.expires_at).toLocaleString()}.`)}catch(e){setMsg(e instanceof Error?e.message:"quote_failed")}finally{setBusy(false)}}
 async function verify(){if(!paymentId||!tx.trim()){setMsg("Create a crypto quote and enter its transaction hash first.");return}setBusy(true);setMsg("Verifying on-chain…");try{const {createClient}=await import("@/utils/supabase/client");const sb=createClient();const {data,error}=await sb.functions.invoke("buildpulse-payment",{body:{action:"subscription_verify",paymentId,txHash:tx.trim()}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||"verification_failed");setMsg(data.state==="confirmed"?"Payment confirmed. Your prepaid BuildPulse Intelligence entitlement is active.":`Payment detected: ${data.confirmations||0}/${data.requiredConfirmations||"?"} confirmations.`)}catch(e){setMsg(e instanceof Error?e.message:"verification_failed")}finally{setBusy(false)}}
 if(!rails.length)return <p className="mt-3 text-[11px] leading-4 text-slate-500">Crypto checkout becomes available here automatically when production settlement rails are configured.</p>;
 return <div className="mt-4 border-t pt-4"><p className="text-xs font-bold">Or pay this term with crypto</p><div className="mt-2 flex flex-wrap gap-2">{rails.map(r=><button type="button" disabled={busy} key={r.asset+r.network} onClick={()=>quote(r)} className="rounded-full border px-3 py-2 text-[11px] font-bold disabled:opacity-50">{r.asset} · {r.network}</button>)}</div>{paymentId&&<div className="mt-3 flex gap-2"><input value={tx} onChange={e=>setTx(e.target.value)} placeholder="Transaction hash" className="min-w-0 flex-1 rounded-lg border px-2 py-2 font-mono text-[10px]"/><button type="button" disabled={busy} onClick={verify} className="rounded-lg bg-slate-950 px-3 py-2 text-[11px] font-bold text-white">Verify</button></div>}{msg&&<p role="status" className="mt-2 break-words text-[11px] leading-4 text-slate-600">{msg}</p>}</div>
}