import "jsr:@supabase/functions-js/edge-runtime.d.ts";import{createClient}from"npm:@supabase/supabase-js@2";
const slugify=(s:string)=>s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
Deno.serve(async(req)=>{const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
 const {data:setting}=await db.from("buildpulse_private_settings").select("value").eq("key","agent_scheduler_secret").maybeSingle();if(!setting?.value||req.headers.get("x-buildpulse-scheduler-secret")!==setting.value)return new Response("unauthorized",{status:401});
 const {data:jobs,error}=await db.rpc("buildpulse_read_story_enrichment",{p_qty:3,p_visibility_seconds:300}) as any;
 if(error||!jobs)return new Response(JSON.stringify({ok:false,error:"queue_read_unavailable"}),{status:500,headers:{"content-type":"application/json"}});
 const out=[];for(const j of jobs){const m=j.message||{};const id=String(m.story_id||"");if(!id)continue;await db.from("buildpulse_story_enrichment_claims").update({state:"processing",attempts:Number(j.read_ct||1),updated_at:new Date().toISOString()}).eq("story_id",id);
  const {data:existing}=await db.from("buildpulse_story_articles").select("id").eq("story_id",id).maybeSingle();if(existing){await db.from("buildpulse_story_enrichment_claims").update({state:"completed",updated_at:new Date().toISOString()}).eq("story_id",id);out.push({story_id:id,status:"already_exists"});continue}
  const headline=String(m.title||"BuildPulse verified brief").slice(0,300);const summary=String(m.summary||"").trim().slice(0,1800);const source=String(m.canonical_source_url||"");
  const body=summary?summary+"\n\nThis BuildPulse brief is based on the verified source record linked below. Additional reporting and context require editorial review before publication.":"This verified story record is queued for additional reporting and editorial review.";
  const row={story_id:id,slug:(slugify(headline)||"story")+"-"+id.slice(0,8),headline,dek:summary.slice(0,300)||null,body_markdown:body,key_facts:summary?[summary]:[],why_it_matters:null,context:null,evidence:source?[{type:"canonical_source",url:source}]:[],hero_image_url:null,hero_image_source_url:m.image_url||null,hero_image_attribution:null,hero_image_rights_status:"unknown",generation_state:"draft",generated_by:"buildpulse-story-enrichment-v1",generated_at:new Date().toISOString()};
  const {error:ins}=await db.from("buildpulse_story_articles").insert(row);if(ins){await db.from("buildpulse_story_enrichment_claims").update({state:"failed",last_error:ins.message.slice(0,500),updated_at:new Date().toISOString()}).eq("story_id",id);out.push({story_id:id,status:"failed"});continue}
  await db.from("buildpulse_story_enrichment_claims").update({state:"completed",updated_at:new Date().toISOString()}).eq("story_id",id);await db.rpc("buildpulse_archive_story_enrichment",{p_msg_id:j.msg_id});out.push({story_id:id,status:"drafted"});}
 return new Response(JSON.stringify({ok:true,processed:out.length,results:out}),{headers:{"content-type":"application/json"}})});