import {createAdminClient} from "@/lib/supabase/admin";
import {buildPulsePublicUrl} from "@/lib/buildpulse/public-origin";
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
export async function GET(){
 const db=createAdminClient();
 const fetchAll=async(table:"buildpulse_editions"|"buildpulse_technology_articles"|"buildpulse_contributor_submissions",select:string,filters:(q:any)=>any)=>{if(!db)return[];const out:any[]=[];for(let from=0;from<49000;from+=1000){let q=db.from(table).select(select).order("published_at",{ascending:false}).range(from,from+999);q=filters(q);const {data:rows,error}=await q;if(error)break;out.push(...(rows??[]));if((rows??[]).length<1000)break}return out};
 const [data,technology,contributors]=await Promise.all([fetchAll("buildpulse_editions","slug,published_at,updated_at",q=>q.in("status",["published","sending","sent"]).eq("archive_visible",true).not("published_at","is",null)),fetchAll("buildpulse_technology_articles","slug,published_at",q=>q.eq("status","published").not("published_at","is",null)),fetchAll("buildpulse_contributor_submissions","id,published_at",q=>q.eq("status","published").not("published_at","is",null))]);
 const base=buildPulsePublicUrl();
 const paths=["","/archive","/markets","/markets/crypto","/markets/exchanges","/markets/indices-metals","/markets/macro","/world","/technology","/news/science","/news/health","/news/culture","/news/life","/news/economy","/news/politics","/news/ai","/news/blockchain","/news/security","/people","/sports","/arts","/arts/visual","/arts/music","/arts/museums","/arts/design","/arts/showcase","/marketplace","/marketplace/safety","/connections","/methodology","/about","/corrections","/ai-editorial-system","/advertise","/contributor-terms","/privacy","/terms","/cookies","/disclosure","/status"];
 const fixed=paths.map(path=>base+path);
 const entries=[...fixed.map(loc=>`<url><loc>${esc(loc)}</loc></url>`),...data.map((e:any)=>`<url><loc>${esc(`${base}/archive/${encodeURIComponent(e.slug)}`)}</loc>${e.updated_at||e.published_at?`<lastmod>${new Date(e.updated_at||e.published_at).toISOString()}</lastmod>`:""}</url>`),...technology.map((a:any)=>`<url><loc>${esc(`${base}/technology/${encodeURIComponent(a.slug)}`)}</loc>${a.published_at?`<lastmod>${new Date(a.published_at).toISOString()}</lastmod>`:""}</url>`),...contributors.map((a:any)=>`<url><loc>${esc(`${base}/contributors/${encodeURIComponent(a.id)}`)}</loc><lastmod>${new Date(a.published_at).toISOString()}</lastmod></url>`)];
 const urls=entries.slice(0,49900).join("");
 return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`,{headers:{"content-type":"application/xml; charset=utf-8","cache-control":"public, max-age=300, s-maxage=300"}});
}