import {fredLatest,marketQuote} from "@/lib/buildpulse/market-providers";
import {NextRequest,NextResponse} from "next/server";

type Group="crypto"|"fx"|"equities"|"indices"|"metals"|"energy"|"macro";
type Q={symbol:string;label:string;value:string;numericValue?:number;currency?:string;maximumFractionDigits?:number;delta?:string;change?:number;group:Group;provider:string;observedAt:string;realtime?:boolean;unit?:string};
const pct=(a:number,b:number)=>b?((a-b)/b)*100:0;
async function j(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{signal:c.signal,next:{revalidate:120},headers:{"user-agent":"BuildPulse/1.0"}});if(!r.ok)throw new Error("market_source_"+r.status);return await r.json()}finally{clearTimeout(t)}}
const groups=new Set<Group>(["crypto","fx","equities","indices","metals","energy","macro"]);
const specs:{symbol:string;label:string;group:Group;currency?:string;digits?:number}[]=[
 {symbol:"AAPL",label:"Apple",group:"equities",currency:"USD",digits:2},{symbol:"MSFT",label:"Microsoft",group:"equities",currency:"USD",digits:2},{symbol:"NVDA",label:"NVIDIA",group:"equities",currency:"USD",digits:2},
 {symbol:"SPY",label:"S&P 500 ETF",group:"indices",currency:"USD",digits:2},{symbol:"QQQ",label:"Nasdaq 100 ETF",group:"indices",currency:"USD",digits:2},{symbol:"DIA",label:"Dow Jones ETF",group:"indices",currency:"USD",digits:2},{symbol:"EWG",label:"Germany ETF",group:"indices",currency:"USD",digits:2},{symbol:"EWU",label:"United Kingdom ETF",group:"indices",currency:"USD",digits:2},{symbol:"EWJ",label:"Japan ETF",group:"indices",currency:"USD",digits:2},
 {symbol:"GLD",label:"Gold · ETF proxy",group:"metals",currency:"USD",digits:2},{symbol:"SLV",label:"Silver · ETF proxy",group:"metals",currency:"USD",digits:2},{symbol:"CPER",label:"Copper · ETF proxy",group:"metals",currency:"USD",digits:2},
 {symbol:"USO",label:"WTI crude · ETF proxy",group:"energy",currency:"USD",digits:2},{symbol:"BNO",label:"Brent crude · ETF proxy",group:"energy",currency:"USD",digits:2}
];
const macro=[["CPIAUCSL","US CPI","Index"],["UNRATE","US unemployment","%"],["FEDFUNDS","Fed funds rate","%"],["GDPC1","US real GDP","Billions chained 2017 USD"],["DGS10","US 10Y Treasury","%"]] as const;

export async function GET(req:NextRequest){
 const requested=req.nextUrl.searchParams.get("group") as Group|null;
 const filter=requested&&groups.has(requested)?requested:null;
 const quotes:Q[]=[];const warnings:string[]=[];
 const wanted=specs.filter(x=>!filter||x.group===filter);
 if(wanted.length)await Promise.all(wanted.map(async s=>{try{const q=await marketQuote(s.symbol);if(q)quotes.push({symbol:s.symbol,label:s.label,value:String(q.price),numericValue:q.price,currency:q.currency||s.currency,maximumFractionDigits:s.digits,group:s.group,provider:q.provider,observedAt:q.timestamp,realtime:q.realtime});else warnings.push("No licensed quote returned for "+s.symbol)}catch(e){warnings.push(s.symbol+": "+(e instanceof Error?e.message:"provider failure"))}}));
 if(!filter||filter==="crypto")try{const x=await j("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,ripple,solana,binancecoin,cardano,dogecoin&vs_currencies=usd&include_24hr_change=true");for(const [id,symbol,label] of [["bitcoin","BTC","Bitcoin"],["ethereum","ETH","Ethereum"],["ripple","XRP","XRP"],["solana","SOL","Solana"],["binancecoin","BNB","BNB"],["cardano","ADA","Cardano"],["dogecoin","DOGE","Dogecoin"]] as const){const v=x?.[id]?.usd,c=x?.[id]?.usd_24h_change;if(Number.isFinite(v))quotes.push({symbol,label,value:String(v),numericValue:Number(v),currency:"USD",maximumFractionDigits:v<10?4:2,change:Number.isFinite(c)?Number(c):undefined,delta:Number.isFinite(c)?(c>=0?"+":"")+c.toFixed(2)+"%":undefined,group:"crypto",provider:"CoinGecko",observedAt:new Date().toISOString(),realtime:false})}}catch(e){warnings.push("CoinGecko: "+(e instanceof Error?e.message:"provider failure"))}
 if(!filter||filter==="fx")try{const rows=await j("https://api.frankfurter.dev/v2/rates?base=usd&quotes=eur,gbp,jpy,chf,try&from="+new Date(Date.now()-7*864e5).toISOString().slice(0,10));for(const [quote,symbol,label,invert] of [["EUR","EUR/USD","Euro",true],["GBP","GBP/USD","Sterling",true],["JPY","USD/JPY","Yen",false],["CHF","USD/CHF","Swiss franc",false],["TRY","USD/TRY","Turkish lira",false]] as const){const a=(rows as any[]).filter(r=>r.quote===quote).sort((x,y)=>x.date.localeCompare(y.date));if(a.length){const cur=Number(a.at(-1).rate),prev=Number(a.at(-2)?.rate??cur),v=invert?1/cur:cur,p=invert?1/prev:prev,c=pct(v,p);quotes.push({symbol,label,value:v.toFixed(symbol.includes("JPY")?2:4),numericValue:v,change:c,delta:(c>=0?"+":"")+c.toFixed(2)+"%",group:"fx",provider:"Frankfurter / ECB reference rates",observedAt:a.at(-1).date+"T00:00:00Z",realtime:false})}}}catch(e){warnings.push("FX: "+(e instanceof Error?e.message:"provider failure"))}
 if(!filter||filter==="macro")await Promise.all(macro.map(async([seriesId,label,unit])=>{try{const x=await fredLatest(seriesId);if(x)quotes.push({symbol:seriesId,label,value:String(x.value),numericValue:x.value,group:"macro",provider:x.provider,observedAt:x.date+"T00:00:00Z",realtime:false,unit})}catch(e){warnings.push("FRED "+seriesId+": "+(e instanceof Error?e.message:"provider failure"))}}));
 quotes.sort((a,b)=>a.group.localeCompare(b.group)||a.label.localeCompare(b.label));
 return NextResponse.json({ok:quotes.length>0,asOf:new Date().toISOString(),group:filter??"all",quotes,warnings},{headers:{"cache-control":"public, s-maxage=60, stale-while-revalidate=300"}});
}