import {marketQuote} from "@/lib/buildpulse/market-providers";
import {NextResponse} from "next/server";
type Q={symbol:string;label:string;value:string;delta?:string;change?:number;group:"crypto"|"fx"|"markets"};
async function j(url:string){const r=await fetch(url,{next:{revalidate:120},headers:{"user-agent":"BuildPulse/1.0"}});if(!r.ok)throw new Error("market_source_failed");return r.json()}
const pct=(a:number,b:number)=>b?((a-b)/b)*100:0;
export async function GET(){const quotes:Q[]=[];
try{const live=await Promise.all([["AAPL","Apple"],["MSFT","Microsoft"],["NVDA","NVIDIA"]].map(async([symbol,label])=>({label,q:await marketQuote(symbol)})));for(const x of live){if(x.q)quotes.push({symbol:x.q.symbol,label:x.label,value:"$"+x.q.price.toLocaleString("en-US",{maximumFractionDigits:2}),group:"markets"})}}catch{}
try{const x=await j("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,ripple,solana&vs_currencies=usd&include_24hr_change=true");for(const [id,symbol,label] of [["bitcoin","BTC","Bitcoin"],["ethereum","ETH","Ethereum"],["ripple","XRP","XRP"],["solana","SOL","Solana"]] as const){const v=x?.[id]?.usd,c=x?.[id]?.usd_24h_change;if(Number.isFinite(v))quotes.push({symbol,label,value:"$"+Number(v).toLocaleString("en-US",{maximumFractionDigits:v<10?4:2}),change:Number.isFinite(c)?c:undefined,delta:Number.isFinite(c)?(c>=0?"+":"")+c.toFixed(2)+"%":undefined,group:"crypto"})}}catch{}
try{const rows=await j("https://api.frankfurter.dev/v2/rates?base=usd&quotes=eur,gbp,jpy,chf&from="+new Date(Date.now()-5*864e5).toISOString().slice(0,10));for(const [quote,symbol,label,invert] of [["EUR","EUR/USD","Euro",true],["GBP","GBP/USD","Sterling",true],["JPY","USD/JPY","Yen",false],["CHF","USD/CHF","Swiss franc",false]] as const){const a=(rows as any[]).filter(r=>r.quote===quote).sort((x,y)=>x.date.localeCompare(y.date));if(a.length){const cur=Number(a.at(-1).rate),prev=Number(a.at(-2)?.rate??cur),v=invert?1/cur:cur,p=invert?1/prev:prev,c=pct(v,p);quotes.push({symbol,label,value:v.toFixed(symbol.includes("JPY")?2:4),change:c,delta:(c>=0?"+":"")+c.toFixed(2)+"%",group:"fx"})}}}catch{}
return NextResponse.json({ok:quotes.length>0,asOf:new Date().toISOString(),quotes},{headers:{"cache-control":"public, s-maxage=120, stale-while-revalidate=300"}})}