import {createAdminClient} from "@/lib/supabase/admin";
export type BuildPulseAiTask="news_draft"|"localize"|"summarize"|"moderation_triage"|"finance_reconcile"|"seo"|"ops";
export type BuildPulseAiRequest={task:BuildPulseAiTask;system:string;input:string;maxOutputTokens?:number;temperature?:number};
export type BuildPulseAiResult={provider:string;model:string;text:string;usage?:Record<string,unknown>};
type Provider="nvidia"|"openai"|"local";
const env=(k:string)=>process.env[k]?.trim();
const providers=(v:string):Provider[]=>v.split(",").map(x=>x.trim()).filter((x):x is Provider=>["local","nvidia","openai"].includes(x));
async function budgetAllowed(task:BuildPulseAiTask){const db=createAdminClient();if(!db)return false;const {data:b}=await db.from("buildpulse_ai_budgets").select("daily_token_limit,daily_request_limit,enabled").eq("task",task).maybeSingle();if(!b)return false;if(!b.enabled)return false;const since=new Date();since.setUTCHours(0,0,0,0);const {data:events}=await db.from("buildpulse_ai_usage_events").select("total_tokens").eq("task",task).eq("status","success").gte("created_at",since.toISOString());const rows=events??[],tokens=rows.reduce((n:any,e:any)=>n+Number(e.total_tokens??0),0);return !(b.daily_request_limit!=null&&rows.length>=b.daily_request_limit)&&!(b.daily_token_limit!=null&&tokens>=Number(b.daily_token_limit))}
async function recordUsage(task:BuildPulseAiTask,p:Provider,model:string,status:"success"|"failure",durationMs:number,attempt:number,usage?:Record<string,unknown>,error?:string){const db=createAdminClient();if(!db)return;const u:any=usage??{};await db.from("buildpulse_ai_usage_events").insert({task,provider:p,model,status,input_tokens:u.prompt_tokens??u.input_tokens??null,output_tokens:u.completion_tokens??u.output_tokens??null,total_tokens:u.total_tokens??null,duration_ms:durationMs,attempt,error_code:error?.slice(0,240)??null})}
function order(task:BuildPulseAiTask):Provider[]{const taskKey="BUILDPULSE_AI_PROVIDER_ORDER_"+task.toUpperCase();const configured=providers(env(taskKey)||env("BUILDPULSE_AI_PROVIDER_ORDER")||"local,nvidia,openai");return configured.length?configured:["local","nvidia","openai"]}
async function callOpenAiLike(base:string,key:string|undefined,model:string,provider:string,r:BuildPulseAiRequest):Promise<BuildPulseAiResult>{
 const timeout=Math.max(5000,Math.min(120000,Number(env("BUILDPULSE_AI_TIMEOUT_MS")||30000)));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
 try{const res=await fetch(base.replace(/\/$/,"")+"/chat/completions",{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",...(key?{authorization:`Bearer ${key}`}:{})},body:JSON.stringify({model,messages:[{role:"system",content:r.system},{role:"user",content:r.input}],temperature:r.temperature??0.2,max_tokens:Math.max(64,Math.min(4096,r.maxOutputTokens??1200))})});if(!res.ok)throw new Error(`AI provider error ${res.status}`);const data=await res.json();const text=data.choices?.[0]?.message?.content??"";if(!text.trim())throw new Error("AI provider returned empty output");return{provider,model,text,usage:data.usage}}finally{clearTimeout(timer)}
}
export async function runBuildPulseAi(r:BuildPulseAiRequest):Promise<BuildPulseAiResult>{
 if(!(await budgetAllowed(r.task)))throw new Error("BuildPulse AI budget disabled or exhausted for task "+r.task);
 const errors:string[]=[];const retries=Math.max(0,Math.min(2,Number(env("BUILDPULSE_AI_RETRIES")||1)));
 for(const p of order(r.task)){for(let attempt=0;attempt<=retries;attempt++){const started=Date.now();try{let out:BuildPulseAiResult|undefined;
  if(p==="local"){const base=env("BUILDPULSE_LOCAL_AI_BASE_URL");if(!base)break;out=await callOpenAiLike(base,env("BUILDPULSE_LOCAL_AI_API_KEY"),env("BUILDPULSE_LOCAL_AI_MODEL")||"local",p,r)}
  if(p==="nvidia"){const key=env("NVIDIA_NIM_API_KEY")||env("NVIDIA_API_KEY");if(!key)break;out=await callOpenAiLike(env("NVIDIA_NIM_BASE_URL")||"https://integrate.api.nvidia.com/v1",key,env("NVIDIA_NIM_MODEL")||"meta/llama-3.1-70b-instruct",p,r)}
  if(p==="openai"){const key=env("OPENAI_API_KEY");if(!key)break;out=await callOpenAiLike(env("OPENAI_BASE_URL")||"https://api.openai.com/v1",key,env("OPENAI_MODEL")||"gpt-5.6-luna",p,r)}
  if(out){const durationMs=Date.now()-started;console.info("buildpulse_ai_success",{task:r.task,provider:p,model:out.model,attempt:attempt+1,durationMs,usage:out.usage});await recordUsage(r.task,p,out.model,"success",durationMs,attempt+1,out.usage);return out}
 }catch(e){const message=e instanceof Error?e.message:"failed";const durationMs=Date.now()-started;errors.push(`${p} attempt ${attempt+1}: ${message}`);console.warn("buildpulse_ai_failure",{task:r.task,provider:p,attempt:attempt+1,durationMs,error:message});await recordUsage(r.task,p,"unknown","failure",durationMs,attempt+1,undefined,message)}}}
 throw new Error("No BuildPulse AI provider available"+(errors.length?": "+errors.join("; "):""))
}