export type BuildPulseAiTask="news_draft"|"localize"|"summarize"|"moderation_triage"|"finance_reconcile"|"seo"|"ops";
export type BuildPulseAiRequest={task:BuildPulseAiTask;system:string;input:string;maxOutputTokens?:number;temperature?:number};
export type BuildPulseAiResult={provider:string;model:string;text:string;usage?:Record<string,unknown>};
type Provider="nvidia"|"openai"|"local";
const json=async(r:Response)=>{if(!r.ok)throw new Error(`AI provider error ${r.status}`);return r.json()};
const env=(k:string)=>process.env[k]?.trim();
function order(task:BuildPulseAiTask):Provider[]{const configured=(env("BUILDPULSE_AI_PROVIDER_ORDER")||"local,nvidia,openai").split(",").map(x=>x.trim()).filter(x=>["local","nvidia","openai"].includes(x)) as Provider[];return configured.length?configured:["local","nvidia","openai"]}
async function callOpenAiLike(base:string,key:string|undefined,model:string,provider:string,r:BuildPulseAiRequest):Promise<BuildPulseAiResult>{const res=await fetch(base.replace(/\/$/,"")+"/chat/completions",{method:"POST",headers:{"content-type":"application/json",...(key?{authorization:`Bearer ${key}`}:{})},body:JSON.stringify({model,messages:[{role:"system",content:r.system},{role:"user",content:r.input}],temperature:r.temperature??0.2,max_tokens:r.maxOutputTokens??1200})});const data=await json(res);return{provider,model,text:data.choices?.[0]?.message?.content??"",usage:data.usage}}
export async function runBuildPulseAi(r:BuildPulseAiRequest):Promise<BuildPulseAiResult>{const errors:string[]=[];for(const p of order(r.task)){try{if(p==="local"){const base=env("BUILDPULSE_LOCAL_AI_BASE_URL");if(!base)continue;return await callOpenAiLike(base,env("BUILDPULSE_LOCAL_AI_API_KEY"),env("BUILDPULSE_LOCAL_AI_MODEL")||"local",p,r)}if(p==="nvidia"){const key=env("NVIDIA_NIM_API_KEY");if(!key)continue;return await callOpenAiLike(env("NVIDIA_NIM_BASE_URL")||"https://integrate.api.nvidia.com/v1",key,env("NVIDIA_NIM_MODEL")||"meta/llama-3.1-70b-instruct",p,r)}if(p==="openai"){const key=env("OPENAI_API_KEY");if(!key)continue;return await callOpenAiLike(env("OPENAI_BASE_URL")||"https://api.openai.com/v1",key,env("OPENAI_MODEL")||"gpt-5.6-luna",p,r)}}catch(e){errors.push(`${p}: ${e instanceof Error?e.message:"failed"}`)}}throw new Error("No BuildPulse AI provider available"+(errors.length?": "+errors.join("; "):""))}
