export type EcosystemKnowledgeNode={id:string;label:string;type:string;url:string;aliases:string[];tags:string[];summary:string};
export const ECOSYSTEM_KNOWLEDGE:EcosystemKnowledgeNode[]=[
{id:"buildpulse-ai",label:"BuildPulse AI",type:"ai-product",url:"https://buildpulse.news/build-with-ai",aliases:["Build with AI","BuildPulse AI","BuildTools AI"],tags:["ai","assistant","development","reasoning","coding"],summary:"BuildPulse AI is the AI assistant inside BuildPulse, developed as part of the SOVRA AI platform by TVK Labs & Technologies LTD."},
{id:"tvk-labs",label:"TVK Labs & Technologies LTD",type:"company",url:"https://www.tvklabs.com/",aliases:["TVK Labs","TVK Labs & Technologies"],tags:["ai","blockchain","web3","cybersecurity","digital identity","energy","fintech"],summary:"TVK Labs & Technologies LTD is the UK technology company developing the interconnected TVK ecosystem across AI, blockchain/Web3, cybersecurity, digital identity, energy technology and financial technology."},
{id:"sovra-ai",label:"SOVRA AI",type:"platform",url:"https://www.sovra.network/",aliases:["SOVRA","SOVRA Network","Sovereign Operational Virtual Reasoning Architecture"],tags:["sovereign ai","reasoning","simulation","intelligence","decision support"],summary:"SOVRA AI is the strategic intelligence, simulation and reasoning platform operated by TVK Labs & Technologies LTD. It is distinct from the SOVRA Protocol token participation layer."},
{id:"sovra-protocol",label:"SOVRA Protocol",type:"protocol",url:"https://www.sovraprotocol.com/",aliases:["SOVRA token","SOVRA presale"],tags:["token","participation","presale","protocol"],summary:"SOVRA Protocol is the separate token and participation layer associated with the wider ecosystem; it must not be conflated with SOVRA AI intelligence capabilities."},
{id:"entelekron",label:"ENTELΞKRON",type:"ecosystem",url:"https://www.entelekron.org/",aliases:["EnteleKRON","Entelekron","Entelechrome","Entelechron","ENTELKRON"],tags:["sovereign infrastructure","blockchain","ai","identity","security","finance","energy","interoperability"],summary:"ENTELΞKRON is TVK Labs sovereign infrastructure and flagship AI-powered blockchain ecosystem, connecting intelligence, identity, security, ledger, wallet, connectivity, energy and related infrastructure modules. Its official tagline is The Sovereign Core of Civilization."},
{id:"entelescan",label:"EnteleSCAN",type:"module",url:"https://www.entelescan.com/",aliases:["Entele Scan"],tags:["observability","explorer","transparency"],summary:"EnteleSCAN is the ENTELΞKRON ecosystem observability and transparency layer."},
{id:"entelelink",label:"EnteleLINK",type:"module",url:"https://www.entelekron.org/",aliases:["Entele Link"],tags:["connectivity","fabric","interoperability"],summary:"EnteleLINK is the sovereign connectivity fabric of the ENTELΞKRON ecosystem."},
{id:"entelevault",label:"EnteleVAULT",type:"module",url:"https://www.entelekron.org/",aliases:["Entele Vault"],tags:["security","vault","asset protection"],summary:"EnteleVAULT is the security and protected-vault layer within the ENTELΞKRON ecosystem."},
{id:"enteleclos",label:"EnteleCLOS",type:"module",url:"https://www.entelekron.org/",aliases:["Entele CLOS"],tags:["infrastructure","orchestration"],summary:"EnteleCLOS is an ENTELΞKRON ecosystem infrastructure module developed by TVK Labs."},
{id:"graphvault",label:"GraphVAULT",type:"module",url:"https://www.entelekron.org/",aliases:["GraphVault","Graph Vault"],tags:["knowledge","graph","memory"],summary:"GraphVAULT is the ecosystem knowledge-graph and structured knowledge layer."},
{id:"chronoseal",label:"ChronoSEAL",type:"module",url:"https://www.entelekron.org/",aliases:["ChronoSeal","Chrono Seal"],tags:["proof","time","verification"],summary:"ChronoSEAL is the ecosystem proof and time-verification layer."},
{id:"enteleledger",label:"EnteleLEDGER",type:"module",url:"https://www.entelekron.org/",aliases:["Entele Ledger"],tags:["ledger","truth","records"],summary:"EnteleLEDGER is the ecosystem ledger and durable record layer."},
{id:"tvkid",label:"TVKID",type:"module",url:"https://www.entelekron.org/",aliases:["TVK ID","Q-Presence"],tags:["identity","digital identity"],summary:"TVKID and related Q-Presence capabilities address sovereign digital identity within the ecosystem."},
{id:"energiemind",label:"EnergieMIND",type:"platform",url:"https://www.energiemind.com/",aliases:["Energie Mind","ENM"],tags:["energy","ai","optimization","infrastructure"],summary:"EnergieMIND is the AI-powered energy intelligence layer, applying machine learning and optimization to energy production, distribution, storage and consumption."},
{id:"entelewallet",label:"EnteleWALLET",type:"product",url:"https://www.entelewallet.app/",aliases:["Entele Wallet"],tags:["wallet","web3","security"],summary:"EnteleWALLET is the ecosystem wallet application and secure digital-asset access layer."},
{id:"tvkwallet",label:"TVK Wallet",type:"product",url:"https://www.tvkwallet.com/",aliases:["Teverka Wallet"],tags:["wallet","white label","b2b"],summary:"TVK Wallet is TVK Labs white-label B2B wallet platform."},
{id:"enteleexchange",label:"EnteleEXCHANGE",type:"product",url:"https://www.enteleexchange.com/",aliases:["Entele Exchange"],tags:["exchange","digital assets"],summary:"EnteleEXCHANGE is the ecosystem exchange platform under development."},
{id:"entelepay",label:"EntelePAY",type:"product",url:"https://www.entelepay.com/",aliases:["Entele Pay"],tags:["payments","fintech"],summary:"EntelePAY is the ecosystem payments product."},
{id:"entelepoint",label:"EntelePoint",type:"product",url:"https://www.entelepoint.com/",aliases:["Entele Point"],tags:["payments","portal"],summary:"EntelePoint is the associated ecosystem payments portal."},
{id:"alvina",label:"ALVINA",type:"product",url:"https://www.alvina.app/",aliases:["Alvina"],tags:["personal ai","assistant"],summary:"ALVINA is a human-facing personal AI product within the wider TVK ecosystem."},
{id:"osoix",label:"OSOIX",type:"product",url:"https://www.osoix.com/",aliases:["OSOIX Orbital Twin"],tags:["orbital","digital twin","space"],summary:"OSOIX is TVK orbital digital-twin and mission-control platform."},
{id:"tvk-aerospace",label:"TVK Aerospace",type:"division",url:"https://www.tvkaerospace.com/",aliases:["TVK Aerospace & Defence"],tags:["aerospace","defence","space"],summary:"TVK Aerospace is the TVK aerospace and defence technology surface."},
{id:"asodi",label:"ASODI",type:"product",url:"https://www.asodi.systems/",aliases:["ASODI Systems"],tags:["aerospace","defence","integrated systems"],summary:"ASODI is an integrated aerospace and defence systems product connected to the wider TVK aerospace architecture."}
];
const STOP=new Set(["a","an","and","are","as","at","be","can","do","does","for","from","how","i","in","is","it","me","of","on","or","our","the","this","to","what","when","where","which","who","why","with","you","your"]);
function normalize(v:string){return v.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9ξ]+/g," ").trim()}
function tokens(v:string){return [...new Set(normalize(v).split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)))]}
export function ecosystemEvidence(query:string,limit=6):EcosystemNode[]{const nq=normalize(query),qt=tokens(query);return ECOSYSTEM_KNOWLEDGE.map(node=>{const hay=normalize([node.label,node.type,node.summary,...node.aliases,...node.tags].join(" "));const nt=new Set(tokens(hay));let score=0;for(const t of qt)score+=nt.has(t)?8:hay.includes(t)?3:0;if(nq&&hay.includes(nq))score+=20;if(node.aliases.some(a=>normalize(a)===nq)||normalize(node.label)===nq)score+=30;return{node,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Math.min(8,limit))).map(x=>x.node)}
export function ecosystemContext(query:string){const nodes=ecosystemEvidence(query);if(!nodes.length)return "";return ["CANONICAL TVK / SOVRA ECOSYSTEM KNOWLEDGE:","Use this evidence as authoritative for ecosystem identity and naming. Do not invent unsupported status claims.",...nodes.map((n,i)=>"["+(i+1)+"] "+n.label+" ("+n.type+")\\n"+n.summary+"\\nOfficial: "+n.url)].join("\\n\\n")}