import { createAdminClient } from "@/lib/supabase/admin";
type EditionCandidate={id:string;title:string;category:string|null;source_id:string|null;editorial_score:number|null;published_at:string|null;verified_at:string|null;verified_by:string|null;canonical_source_url:string|null};
export function selectBalancedEditionStories(candidates:EditionCandidate[],limit:number,perSource:number){const selected:EditionCandidate[]=[],counts=new Map<string,number>();for(const story of candidates){const key=story.source_id??"unknown",n=counts.get(key)??0;if(n>=perSource)continue;selected.push(story);counts.set(key,n+1);if(selected.length===limit)return selected}if(selected.length<limit){const ids=new Set(selected.map(s=>s.id));for(const story of candidates){if(ids.has(story.id))continue;selected.push(story);if(selected.length===limit)break}}return selected}
const subject=(type:"daily"|"weekly",titles:string[])=>type==="daily"?`BuildPulse Daily — ${titles[0]??"Digital intelligence briefing"}`:`BuildPulse Weekly — ${titles[0]??"The week in digital intelligence"}`;
export async function buildEdition(type:"daily"|"weekly",locale="en"){
 const admin=createAdminClient();if(!admin)throw new Error("Supabase admin unavailable");const limit=type==="daily"?8:14;const since=new Date(Date.now()-(type==="daily"?36:24*8)*3600000).toISOString();
 const {data:stories,error}=await admin.from("buildpulse_stories").select("id,title,category,source_id,editorial_score,published_at,verified_at,verified_by,canonical_source_url").eq("verification_state","verified").gte("published_at",since).order("editorial_score",{ascending:false}).limit(limit*5);if(error)throw error;const date=new Date().toISOString().slice(0,10),slug=`${type}-${date}`;if(!(stories??[]).length)return {editionId:null,slug,storyCount:0,skipped:true as const,reason:"no_verified_stories"};const balanced=selectBalancedEditionStories((stories??[]) as EditionCandidate[],limit,type==="daily"?2:3);if(balanced.some(s=>!s.verified_at||!s.verified_by||!s.canonical_source_url))throw new Error("Verified story is missing review provenance");
 const storiesSelected=balanced;const generationKey=`${type}:${locale}:${date}`;const titles=storiesSelected.map(x=>x.title),metadata={strategy:"verified-score-source-balanced-v2",generatedAt:new Date().toISOString(),storyCount:storiesSelected.length};
 const {data:eid,error:ee}=await (admin.rpc as any)("buildpulse_claim_edition_generation",{p_generation_key:generationKey,p_edition_type:type,p_locale:locale,p_subject:subject(type,titles),p_preheader:type==="daily"?"The essential AI, blockchain, markets and security signal.":"The week's connected view across digital infrastructure.",p_slug:slug,p_metadata:metadata});if(ee)throw ee;if(!eid)return {editionId:null,slug,storyCount:0,skipped:true as const,reason:"generation_already_claimed"};const editionId=eid as string;
 try{await admin.from("buildpulse_edition_stories").delete().eq("edition_id",editionId);let pos=0;for(const s of storiesSelected){const {error:linkError}=await admin.from("buildpulse_edition_stories").insert({edition_id:editionId,story_id:s.id,section:s.category||"lead",position:pos++});if(linkError)throw linkError}await admin.from("buildpulse_editions").update({generation_completed_at:new Date().toISOString(),generation_error:null}).eq("id",editionId);return {editionId,slug,storyCount:storiesSelected.length,skipped:false as const}}
 catch(e){await admin.from("buildpulse_editions").update({generation_error:(e instanceof Error?e.message:"unknown").slice(0,1000)}).eq("id",editionId);throw e}
}