"use client";
import {useEffect} from "react";
export const BUILDPULSE_LOCALES=["en","de","fr","tr","es","it","pt","ru","pl","nl","sv","no","fi","da","ro","hu","cs","el","bg","uk","zh","ja","ko","ar","hi"] as const;
export type BuildPulseLocale=typeof BUILDPULSE_LOCALES[number];
const KEY="buildpulse.locale",TZ="buildpulse.timeZone",CTX="buildpulse.context";
export type BuildPulseContext={country:string;region:string;city:string;timezone:string;localeHint:string;source:string;precision:"coarse";ipStored:false};
export function normalizeBuildPulseLocale(input?:string|null):BuildPulseLocale{const x=(input||"en").toLowerCase().replace("_","-"),base=x.split("-")[0];return (BUILDPULSE_LOCALES as readonly string[]).includes(base)?base as BuildPulseLocale:"en"}
export function getDeviceLocale(){if(typeof navigator==="undefined")return "en" as BuildPulseLocale;return normalizeBuildPulseLocale(navigator.languages?.[0]||navigator.language)}
export function getDeviceTimeZone(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"}catch{return"UTC"}}
export function setBuildPulseLocale(locale:string){const l=normalizeBuildPulseLocale(locale);try{localStorage.setItem(KEY,l)}catch{};document.cookie=`bp_locale=${encodeURIComponent(l)}; Path=/; Max-Age=31536000; SameSite=Lax`;document.documentElement.lang=l;document.documentElement.dir=["ar"].includes(l)?"rtl":"ltr";window.dispatchEvent(new CustomEvent("buildpulse:locale",{detail:{locale:l}}))}
export function getBuildPulseLocale(){try{return normalizeBuildPulseLocale(localStorage.getItem(KEY)||getDeviceLocale())}catch{return getDeviceLocale()}}
export function BuildPulseLocalization(){useEffect(()=>{let cancelled=false;const browserLocale=getBuildPulseLocale(),browserTimeZone=getDeviceTimeZone();async function init(){let context:BuildPulseContext|null=null;try{const r=await fetch("/api/buildpulse/context",{cache:"no-store"});if(r.ok)context=await r.json()}catch{}if(cancelled)return;let savedLocale:string|null=null;try{savedLocale=localStorage.getItem(KEY)}catch{}const locale=normalizeBuildPulseLocale(savedLocale||context?.localeHint||browserLocale),timeZone=context?.timezone||browserTimeZone;setBuildPulseLocale(locale);try{localStorage.setItem(TZ,timeZone);if(context)localStorage.setItem(CTX,JSON.stringify(context))}catch{};document.cookie=`bp_timezone=${encodeURIComponent(timeZone)}; Path=/; Max-Age=31536000; SameSite=Lax`;window.dispatchEvent(new CustomEvent("buildpulse:context",{detail:context}))}init();return()=>{cancelled=true}},[]);return null}
export function getBuildPulseContext():BuildPulseContext|null{try{return JSON.parse(localStorage.getItem(CTX)||"null") as BuildPulseContext|null}catch{return null}}
export function getBuildPulseTimeZone(){if(typeof window==="undefined")return "UTC";try{const saved=localStorage.getItem(TZ);if(saved){new Intl.DateTimeFormat("en-US",{timeZone:saved}).format();return saved}}catch{}return getDeviceTimeZone()}
export function formatLocalDate(value:string|number|Date,opts:Intl.DateTimeFormatOptions={dateStyle:"medium",timeStyle:"short"}){const locale=typeof window!=="undefined"?getBuildPulseLocale():"en";return new Intl.DateTimeFormat(locale,{...opts,timeZone:getBuildPulseTimeZone()}).format(new Date(value))}
export function formatLocalNumber(value:number,opts:Intl.NumberFormatOptions={}){const locale=typeof window!=="undefined"?getBuildPulseLocale():"en";return new Intl.NumberFormat(locale,opts).format(value)}
export function formatLocalCurrency(value:number,currency:string,opts:Intl.NumberFormatOptions={}){const code=/^[A-Z]{3}$/.test(currency.toUpperCase())?currency.toUpperCase():"EUR";return formatLocalNumber(value,{style:"currency",currency:code,...opts})}
