import {randomUUID} from "node:crypto";import {ensureBuildPulseEditionPdf} from "@/lib/buildpulse/pdf";import {createAdminClient} from "@/lib/supabase/admin";import {createBuildPulseCampaign,sendBuildPulseCampaignNow} from "@/lib/buildpulse/brevo";
export async function publishBuildPulseEdition(editionId:string){const admin=createAdminClient();if(!admin)throw new Error("Supabase admin unavailable");const {data:e,error}=await admin.from("buildpulse_editions").select("*").eq("id",editionId).single();if(error||!e)throw new Error("Edition not found");if(!["approved","scheduled"].includes(e.status))throw new Error("Edition must be approved before delivery");if(e.founder_review_status!=="approved"||e.founder_approved_revision!==e.revision_number)throw new Error("Founder approval for the current revision is required before delivery");if(!e.body_html)throw new Error("Edition body is not composed");if(e.brevo_campaign_id)return {idempotent:true,campaignId:e.brevo_campaign_id,state:e.brevo_dispatch_state};
await ensureBuildPulseEditionPdf(editionId);
const claim=randomUUID();const {data:claimed,error:claimError}=await admin.rpc("buildpulse_claim_dispatch",{p_edition_id:editionId,p_revision:e.revision_number,p_token:claim});if(claimError)throw new Error("Delivery claim failed");if(!claimed)return {idempotent:true,campaignId:undefined,state:"claimed_by_another_worker"};
let campaign;try{campaign=await createBuildPulseCampaign({name:`BuildPulse ${e.edition_type} ${e.slug}`,subject:e.subject,html:e.body_html})}catch(err){await admin.rpc("buildpulse_release_dispatch_claim",{p_edition_id:editionId,p_token:claim,p_error:"Brevo campaign creation threw"});throw err}
if(!campaign.ok||!campaign.campaignId){await admin.rpc("buildpulse_release_dispatch_claim",{p_edition_id:editionId,p_token:claim,p_error:`Brevo campaign unavailable: ${campaign.ok?"missing_campaign_id":campaign.reason}`});throw new Error("Brevo campaign unavailable")}
const now=new Date().toISOString();const {error:persistError}=await admin.from("buildpulse_editions").update({brevo_campaign_id:campaign.campaignId,brevo_dispatch_state:"campaign_created",brevo_campaign_created_at:now,brevo_dispatch_error:null,status:"approved",updated_at:now}).eq("id",editionId).eq("dispatch_claim_token",claim).is("brevo_campaign_id",null);if(persistError)throw new Error("Campaign created but delivery state could not be persisted; manual reconciliation required");
{const requestedAt=new Date().toISOString();await admin.from("buildpulse_editions").update({brevo_dispatch_state:"send_requested",brevo_send_requested_at:requestedAt,updated_at:requestedAt}).eq("id",editionId).eq("brevo_campaign_id",campaign.campaignId).eq("dispatch_claim_token",claim);const dispatched=await sendBuildPulseCampaignNow(campaign.campaignId);if(!dispatched.ok){await admin.from("buildpulse_editions").update({brevo_dispatch_state:"failed",brevo_dispatch_error:dispatched.reason,updated_at:new Date().toISOString()}).eq("id",editionId).eq("brevo_campaign_id",campaign.campaignId);throw new Error(`Brevo campaign ${campaign.campaignId} persisted but dispatch was not confirmed: ${dispatched.reason}`)}await admin.from("buildpulse_editions").update({status:"sending",brevo_dispatch_state:"send_requested",dispatch_claim_token:null,dispatch_claimed_at:null,updated_at:new Date().toISOString()}).eq("id",editionId).eq("brevo_campaign_id",campaign.campaignId).eq("dispatch_claim_token",claim)}
return {idempotent:false,campaignId:campaign.campaignId,state:"send_requested"}}
