import {lookup} from "node:dns/promises";
import {isIP} from "node:net";

export type FeedItem={id?:string;url:string;title:string;excerpt?:string;publishedAt?:string;raw?:Record<string,unknown>};
function text(v:unknown){return typeof v==="string"?v.trim():""}
function forbiddenIpv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return true;return p[0]===0||p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}
function forbiddenIp(ip:string){if(isIP(ip)===4)return forbiddenIpv4(ip);if(isIP(ip)!==6)return true;const h=ip.toLowerCase();if(h==="::"||h==="::1")return true;if(h.startsWith("fc")||h.startsWith("fd")||/^fe[89ab]/.test(h))return true;const mapped=h.match(/::ffff:(\d+\.\d+\.\d+\.\d+)$/);return mapped?forbiddenIpv4(mapped[1]):false}
function forbiddenHost(host:string){const h=host.toLowerCase().replace(/^\[|\]$/g,"");if(h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||h.endsWith(".internal"))return true;if(isIP(h))return forbiddenIp(h);return false}
export function isSafeBuildPulseUrl(value:string){try{const u=new URL(value);return u.protocol==="https:"&&!u.username&&!u.password&&!forbiddenHost(u.hostname)}catch{return false}}
export async function assertBuildPulseHostResolvesPublic(url:string){const u=new URL(url);const answers=await lookup(u.hostname,{all:true,verbatim:true});if(!answers.length||answers.some(a=>forbiddenIp(a.address)))throw new Error("BuildPulse source resolved to a non-public address");return answers.map(a=>a.address)}

function decodeXml(value:string){return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function xmlTag(block:string,names:string[]){for(const name of names){const m=block.match(new RegExp("<"+name+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+name+">","i"));if(m)return decodeXml(m[1])}return ""}
export function parseXmlFeed(xml:string):FeedItem[]{const blocks=xml.match(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi)??[];return blocks.map(block=>{let url=xmlTag(block,["link","guid"]);const href=block.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*>/i);if(href)url=decodeXml(href[1]);return {id:xmlTag(block,["guid","id"])||undefined,url,title:xmlTag(block,["title"]),excerpt:xmlTag(block,["description","summary","content"])||undefined,publishedAt:xmlTag(block,["pubDate","published","updated"])||undefined,raw:{format:"xml"}}}).filter(item=>Boolean(item.title)&&isSafeBuildPulseUrl(item.url))}
export function parseJsonFeed(payload:unknown):FeedItem[]{if(!payload||typeof payload!=="object")return[];const p=payload as any;const items=Array.isArray(p.items)?p.items:Array.isArray(p.articles)?p.articles:Array.isArray(p.data)?p.data:[];return items.map((x:any)=>({id:text(x.id||x.guid)||undefined,url:text(x.url||x.link),title:text(x.title),excerpt:text(x.summary||x.description||x.excerpt)||undefined,publishedAt:text(x.date_published||x.published_at||x.publishedAt)||undefined,raw:x})).filter((x:FeedItem)=>isSafeBuildPulseUrl(x.url)&&x.title)}
export async function fetchBuildPulseFeed(url:string,signal?:AbortSignal){if(!isSafeBuildPulseUrl(url))throw new Error("Unsafe BuildPulse source URL");let current=url;for(let hop=0;hop<4;hop++){const before=await assertBuildPulseHostResolvesPublic(current);const u=new URL(current);const res=await fetch(u,{headers:{accept:"application/feed+json, application/json, application/rss+xml, application/atom+xml, application/xml, text/xml"},signal,redirect:"manual"});if(res.status>=300&&res.status<400){const location=res.headers.get("location");if(!location)throw new Error("BuildPulse source redirect has no location");const next=new URL(location,current).toString();if(!isSafeBuildPulseUrl(next))throw new Error("BuildPulse source redirect is unsafe");current=next;continue}if(!res.ok)throw new Error(`Source HTTP ${res.status}`);const after=await assertBuildPulseHostResolvesPublic(current);if(before.length!==after.length||before.some(ip=>!after.includes(ip)))throw new Error("BuildPulse source DNS changed during retrieval");const type=(res.headers.get("content-type")??"").toLowerCase();if(!/(json|xml|rss|atom)/i.test(type))throw new Error("BuildPulse source has an unsupported feed type");const len=Number(res.headers.get("content-length")??0);if(len>2_000_000)throw new Error("BuildPulse source exceeds size limit");const body=await res.text();if(body.length>2_000_000)throw new Error("BuildPulse source exceeds size limit");if(/json/i.test(type)){try{return parseJsonFeed(JSON.parse(body))}catch{throw new Error("BuildPulse JSON feed is malformed")}}return parseXmlFeed(body)}throw new Error("BuildPulse source exceeded redirect limit")}
export const fetchJsonFeed=fetchBuildPulseFeed;
