export type UiLocale="en"|"de"|"fr"|"tr"|"es"|"it"|"pt"|"ru"|"pl"|"nl"|"sv"|"no"|"fi"|"da"|"ro"|"hu"|"cs"|"el"|"bg"|"uk"|"zh"|"ja"|"ko"|"ar"|"hi";
const C={
  "en": {
    "news": "News",
    "intelligence": "Intelligence",
    "community": "Community",
    "culture": "Culture",
    "about": "About",
    "subscriptions": "Subscriptions",
    "buildAi": "Build with AI",
    "account": "Account",
    "language": "Language",
    "latest": "Latest",
    "local": "Local",
    "world": "World",
    "technology": "Technology",
    "politics": "Politics",
    "economy": "Economy",
    "markets": "Markets",
    "methodology": "Methodology",
    "social": "Social",
    "blogs": "Blogs",
    "people": "People",
    "connections": "Connections",
    "sports": "Sports",
    "arts": "Arts",
    "marketplace": "Marketplace",
    "aboutBp": "About BuildPulse",
    "contribute": "Contribute",
    "advertise": "Advertise",
    "home": "Home",
    "archive": "Archive",
    "aiEditorial": "AI Editorial System",
    "disclosure": "Disclosure",
    "privacy": "Privacy",
    "terms": "Terms",
    "status": "Status",
    "tagline": "Global Technology & Digital Intelligence"
  },
  "de": {
    "news": "Nachrichten",
    "intelligence": "Intelligence",
    "community": "Community",
    "culture": "Kultur",
    "about": "Über uns",
    "subscriptions": "Abonnements",
    "buildAi": "Mit KI erstellen",
    "account": "Konto",
    "language": "Sprache",
    "latest": "Aktuell",
    "local": "Lokal",
    "world": "Welt",
    "technology": "Technologie",
    "politics": "Politik",
    "economy": "Wirtschaft",
    "markets": "Märkte",
    "methodology": "Methodik",
    "social": "Social",
    "blogs": "Blogs",
    "people": "Personen",
    "connections": "Kontakte",
    "sports": "Sport",
    "arts": "Kunst",
    "marketplace": "Marktplatz",
    "aboutBp": "Über BuildPulse",
    "contribute": "Beitragen",
    "advertise": "Werben",
    "home": "Startseite",
    "archive": "Archiv",
    "aiEditorial": "KI-Redaktionssystem",
    "disclosure": "Offenlegung",
    "privacy": "Datenschutz",
    "terms": "Bedingungen",
    "status": "Status",
    "tagline": "Globale Technologie & digitale Intelligence"
  },
  "fr": {
    "news": "Actualités",
    "intelligence": "Intelligence",
    "community": "Communauté",
    "culture": "Culture",
    "about": "À propos",
    "subscriptions": "Abonnements",
    "buildAi": "Créer avec l’IA",
    "account": "Compte",
    "language": "Langue",
    "latest": "Dernières nouvelles",
    "local": "Local",
    "world": "Monde",
    "technology": "Technologie",
    "politics": "Politique",
    "economy": "Économie",
    "markets": "Marchés",
    "methodology": "Méthodologie",
    "social": "Social",
    "blogs": "Blogs",
    "people": "Personnes",
    "connections": "Connexions",
    "sports": "Sports",
    "arts": "Arts",
    "marketplace": "Marché",
    "aboutBp": "À propos de BuildPulse",
    "contribute": "Contribuer",
    "advertise": "Faire de la publicité",
    "home": "Accueil",
    "archive": "Archives",
    "aiEditorial": "Système éditorial IA",
    "disclosure": "Divulgation",
    "privacy": "Confidentialité",
    "terms": "Conditions",
    "status": "Statut",
    "tagline": "Technologie mondiale et intelligence numérique"
  },
  "tr": {
    "news": "Haberler",
    "intelligence": "İstihbarat",
    "community": "Topluluk",
    "culture": "Kültür",
    "about": "Hakkında",
    "subscriptions": "Abonelikler",
    "buildAi": "AI ile Oluştur",
    "account": "Hesap",
    "language": "Dil",
    "latest": "Son Haberler",
    "local": "Yerel",
    "world": "Dünya",
    "technology": "Teknoloji",
    "politics": "Politika",
    "economy": "Ekonomi",
    "markets": "Piyasalar",
    "methodology": "Metodoloji",
    "social": "Sosyal",
    "blogs": "Bloglar",
    "people": "Kişiler",
    "connections": "Bağlantılar",
    "sports": "Spor",
    "arts": "Sanat",
    "marketplace": "Pazar",
    "aboutBp": "BuildPulse Hakkında",
    "contribute": "Katkıda Bulun",
    "advertise": "Reklam Ver",
    "home": "Ana Sayfa",
    "archive": "Arşiv",
    "aiEditorial": "AI Editoryal Sistemi",
    "disclosure": "Açıklamalar",
    "privacy": "Gizlilik",
    "terms": "Koşullar",
    "status": "Durum",
    "tagline": "Küresel Teknoloji ve Dijital İstihbarat"
  },
  "es": {
    "news": "Noticias",
    "intelligence": "Inteligencia",
    "community": "Comunidad",
    "culture": "Cultura",
    "about": "Acerca de",
    "subscriptions": "Suscripciones",
    "buildAi": "Crear con IA",
    "account": "Cuenta",
    "language": "Idioma",
    "latest": "Últimas",
    "local": "Local",
    "world": "Mundo",
    "technology": "Tecnología",
    "politics": "Política",
    "economy": "Economía",
    "markets": "Mercados",
    "methodology": "Metodología",
    "social": "Social",
    "blogs": "Blogs",
    "people": "Personas",
    "connections": "Conexiones",
    "sports": "Deportes",
    "arts": "Artes",
    "marketplace": "Mercado",
    "aboutBp": "Acerca de BuildPulse",
    "contribute": "Contribuir",
    "advertise": "Anunciar",
    "home": "Inicio",
    "archive": "Archivo",
    "aiEditorial": "Sistema editorial de IA",
    "disclosure": "Divulgación",
    "privacy": "Privacidad",
    "terms": "Términos",
    "status": "Estado",
    "tagline": "Tecnología global e inteligencia digital"
  },
  "it": {
    "news": "Notizie",
    "intelligence": "Intelligence",
    "community": "Comunità",
    "culture": "Cultura",
    "about": "Informazioni",
    "subscriptions": "Abbonamenti",
    "buildAi": "Crea con l’IA",
    "account": "Account",
    "language": "Lingua",
    "latest": "Ultime",
    "local": "Locale",
    "world": "Mondo",
    "technology": "Tecnologia",
    "politics": "Politica",
    "economy": "Economia",
    "markets": "Mercati",
    "methodology": "Metodologia",
    "social": "Social",
    "blogs": "Blog",
    "people": "Persone",
    "connections": "Connessioni",
    "sports": "Sport",
    "arts": "Arti",
    "marketplace": "Mercato",
    "aboutBp": "Informazioni su BuildPulse",
    "contribute": "Contribuisci",
    "advertise": "Pubblicità",
    "home": "Home",
    "archive": "Archivio",
    "aiEditorial": "Sistema editoriale IA",
    "disclosure": "Informativa",
    "privacy": "Privacy",
    "terms": "Termini",
    "status": "Stato",
    "tagline": "Tecnologia globale e intelligence digitale"
  },
  "pt": {
    "news": "Notícias",
    "intelligence": "Inteligência",
    "community": "Comunidade",
    "culture": "Cultura",
    "about": "Sobre",
    "subscriptions": "Assinaturas",
    "buildAi": "Criar com IA",
    "account": "Conta",
    "language": "Idioma",
    "latest": "Últimas",
    "local": "Local",
    "world": "Mundo",
    "technology": "Tecnologia",
    "politics": "Política",
    "economy": "Economia",
    "markets": "Mercados",
    "methodology": "Metodologia",
    "social": "Social",
    "blogs": "Blogs",
    "people": "Pessoas",
    "connections": "Conexões",
    "sports": "Esportes",
    "arts": "Artes",
    "marketplace": "Mercado",
    "aboutBp": "Sobre o BuildPulse",
    "contribute": "Contribuir",
    "advertise": "Anunciar",
    "home": "Início",
    "archive": "Arquivo",
    "aiEditorial": "Sistema editorial de IA",
    "disclosure": "Divulgação",
    "privacy": "Privacidade",
    "terms": "Termos",
    "status": "Estado",
    "tagline": "Tecnologia global e inteligência digital"
  },
  "ru": {
    "news": "Новости",
    "intelligence": "Аналитика",
    "community": "Сообщество",
    "culture": "Культура",
    "about": "О нас",
    "subscriptions": "Подписки",
    "buildAi": "Создать с ИИ",
    "account": "Аккаунт",
    "language": "Язык",
    "latest": "Последнее",
    "local": "Местное",
    "world": "Мир",
    "technology": "Технологии",
    "politics": "Политика",
    "economy": "Экономика",
    "markets": "Рынки",
    "methodology": "Методология",
    "social": "Соцсеть",
    "blogs": "Блоги",
    "people": "Люди",
    "connections": "Связи",
    "sports": "Спорт",
    "arts": "Искусство",
    "marketplace": "Маркетплейс",
    "aboutBp": "О BuildPulse",
    "contribute": "Стать автором",
    "advertise": "Реклама",
    "home": "Главная",
    "archive": "Архив",
    "aiEditorial": "Редакционная система ИИ",
    "disclosure": "Раскрытие информации",
    "privacy": "Конфиденциальность",
    "terms": "Условия",
    "status": "Статус",
    "tagline": "Глобальные технологии и цифровая аналитика"
  },
  "pl": {
    "news": "Wiadomości",
    "intelligence": "Analizy",
    "community": "Społeczność",
    "culture": "Kultura",
    "about": "O nas",
    "subscriptions": "Subskrypcje",
    "buildAi": "Twórz z AI",
    "account": "Konto",
    "language": "Język",
    "latest": "Najnowsze",
    "local": "Lokalne",
    "world": "Świat",
    "technology": "Technologia",
    "politics": "Polityka",
    "economy": "Gospodarka",
    "markets": "Rynki",
    "methodology": "Metodologia",
    "social": "Społeczność",
    "blogs": "Blogi",
    "people": "Ludzie",
    "connections": "Kontakty",
    "sports": "Sport",
    "arts": "Sztuka",
    "marketplace": "Rynek",
    "aboutBp": "O BuildPulse",
    "contribute": "Współtwórz",
    "advertise": "Reklama",
    "home": "Strona główna",
    "archive": "Archiwum",
    "aiEditorial": "System redakcyjny AI",
    "disclosure": "Ujawnienia",
    "privacy": "Prywatność",
    "terms": "Warunki",
    "status": "Status",
    "tagline": "Globalna technologia i analityka cyfrowa"
  },
  "nl": {
    "news": "Nieuws",
    "intelligence": "Intelligence",
    "community": "Community",
    "culture": "Cultuur",
    "about": "Over",
    "subscriptions": "Abonnementen",
    "buildAi": "Bouwen met AI",
    "account": "Account",
    "language": "Taal",
    "latest": "Laatste",
    "local": "Lokaal",
    "world": "Wereld",
    "technology": "Technologie",
    "politics": "Politiek",
    "economy": "Economie",
    "markets": "Markten",
    "methodology": "Methodologie",
    "social": "Sociaal",
    "blogs": "Blogs",
    "people": "Mensen",
    "connections": "Connecties",
    "sports": "Sport",
    "arts": "Kunst",
    "marketplace": "Marktplaats",
    "aboutBp": "Over BuildPulse",
    "contribute": "Bijdragen",
    "advertise": "Adverteren",
    "home": "Home",
    "archive": "Archief",
    "aiEditorial": "AI-redactiesysteem",
    "disclosure": "Openbaarmaking",
    "privacy": "Privacy",
    "terms": "Voorwaarden",
    "status": "Status",
    "tagline": "Wereldwijde technologie en digitale intelligence"
  },
  "sv": {
    "news": "Nyheter",
    "intelligence": "Analys",
    "community": "Gemenskap",
    "culture": "Kultur",
    "about": "Om",
    "subscriptions": "Prenumerationer",
    "buildAi": "Bygg med AI",
    "account": "Konto",
    "language": "Språk",
    "latest": "Senaste",
    "local": "Lokalt",
    "world": "Världen",
    "technology": "Teknik",
    "politics": "Politik",
    "economy": "Ekonomi",
    "markets": "Marknader",
    "methodology": "Metodik",
    "social": "Socialt",
    "blogs": "Bloggar",
    "people": "Personer",
    "connections": "Kontakter",
    "sports": "Sport",
    "arts": "Konst",
    "marketplace": "Marknadsplats",
    "aboutBp": "Om BuildPulse",
    "contribute": "Bidra",
    "advertise": "Annonsera",
    "home": "Hem",
    "archive": "Arkiv",
    "aiEditorial": "AI-redaktionssystem",
    "disclosure": "Upplysningar",
    "privacy": "Integritet",
    "terms": "Villkor",
    "status": "Status",
    "tagline": "Global teknik och digital analys"
  },
  "no": {
    "news": "Nyheter",
    "intelligence": "Analyse",
    "community": "Fellesskap",
    "culture": "Kultur",
    "about": "Om",
    "subscriptions": "Abonnementer",
    "buildAi": "Bygg med KI",
    "account": "Konto",
    "language": "Språk",
    "latest": "Siste",
    "local": "Lokalt",
    "world": "Verden",
    "technology": "Teknologi",
    "politics": "Politikk",
    "economy": "Økonomi",
    "markets": "Markeder",
    "methodology": "Metodikk",
    "social": "Sosialt",
    "blogs": "Blogger",
    "people": "Personer",
    "connections": "Forbindelser",
    "sports": "Sport",
    "arts": "Kunst",
    "marketplace": "Markedsplass",
    "aboutBp": "Om BuildPulse",
    "contribute": "Bidra",
    "advertise": "Annonser",
    "home": "Hjem",
    "archive": "Arkiv",
    "aiEditorial": "KI-redaksjonssystem",
    "disclosure": "Opplysninger",
    "privacy": "Personvern",
    "terms": "Vilkår",
    "status": "Status",
    "tagline": "Global teknologi og digital analyse"
  },
  "fi": {
    "news": "Uutiset",
    "intelligence": "Analytiikka",
    "community": "Yhteisö",
    "culture": "Kulttuuri",
    "about": "Tietoa",
    "subscriptions": "Tilaukset",
    "buildAi": "Rakenna tekoälyllä",
    "account": "Tili",
    "language": "Kieli",
    "latest": "Uusimmat",
    "local": "Paikalliset",
    "world": "Maailma",
    "technology": "Teknologia",
    "politics": "Politiikka",
    "economy": "Talous",
    "markets": "Markkinat",
    "methodology": "Menetelmät",
    "social": "Yhteisö",
    "blogs": "Blogit",
    "people": "Ihmiset",
    "connections": "Yhteydet",
    "sports": "Urheilu",
    "arts": "Taide",
    "marketplace": "Markkinapaikka",
    "aboutBp": "Tietoa BuildPulsesta",
    "contribute": "Osallistu",
    "advertise": "Mainosta",
    "home": "Etusivu",
    "archive": "Arkisto",
    "aiEditorial": "Tekoälytoimitusjärjestelmä",
    "disclosure": "Tiedot",
    "privacy": "Tietosuoja",
    "terms": "Ehdot",
    "status": "Tila",
    "tagline": "Globaali teknologia ja digitaalinen analytiikka"
  },
  "da": {
    "news": "Nyheder",
    "intelligence": "Analyse",
    "community": "Fællesskab",
    "culture": "Kultur",
    "about": "Om",
    "subscriptions": "Abonnementer",
    "buildAi": "Byg med AI",
    "account": "Konto",
    "language": "Sprog",
    "latest": "Seneste",
    "local": "Lokalt",
    "world": "Verden",
    "technology": "Teknologi",
    "politics": "Politik",
    "economy": "Økonomi",
    "markets": "Markeder",
    "methodology": "Metode",
    "social": "Socialt",
    "blogs": "Blogs",
    "people": "Personer",
    "connections": "Forbindelser",
    "sports": "Sport",
    "arts": "Kunst",
    "marketplace": "Markedsplads",
    "aboutBp": "Om BuildPulse",
    "contribute": "Bidrag",
    "advertise": "Annoncér",
    "home": "Hjem",
    "archive": "Arkiv",
    "aiEditorial": "AI-redaktionssystem",
    "disclosure": "Oplysninger",
    "privacy": "Privatliv",
    "terms": "Vilkår",
    "status": "Status",
    "tagline": "Global teknologi og digital analyse"
  },
  "ro": {
    "news": "Știri",
    "intelligence": "Analiză",
    "community": "Comunitate",
    "culture": "Cultură",
    "about": "Despre",
    "subscriptions": "Abonamente",
    "buildAi": "Construiește cu AI",
    "account": "Cont",
    "language": "Limbă",
    "latest": "Ultimele",
    "local": "Local",
    "world": "Lume",
    "technology": "Tehnologie",
    "politics": "Politică",
    "economy": "Economie",
    "markets": "Piețe",
    "methodology": "Metodologie",
    "social": "Social",
    "blogs": "Bloguri",
    "people": "Persoane",
    "connections": "Conexiuni",
    "sports": "Sport",
    "arts": "Arte",
    "marketplace": "Piață",
    "aboutBp": "Despre BuildPulse",
    "contribute": "Contribuie",
    "advertise": "Publicitate",
    "home": "Acasă",
    "archive": "Arhivă",
    "aiEditorial": "Sistem editorial AI",
    "disclosure": "Dezvăluiri",
    "privacy": "Confidențialitate",
    "terms": "Termeni",
    "status": "Stare",
    "tagline": "Tehnologie globală și analiză digitală"
  },
  "hu": {
    "news": "Hírek",
    "intelligence": "Elemzés",
    "community": "Közösség",
    "culture": "Kultúra",
    "about": "Rólunk",
    "subscriptions": "Előfizetések",
    "buildAi": "Építs MI-vel",
    "account": "Fiók",
    "language": "Nyelv",
    "latest": "Legfrissebb",
    "local": "Helyi",
    "world": "Világ",
    "technology": "Technológia",
    "politics": "Politika",
    "economy": "Gazdaság",
    "markets": "Piacok",
    "methodology": "Módszertan",
    "social": "Közösségi",
    "blogs": "Blogok",
    "people": "Emberek",
    "connections": "Kapcsolatok",
    "sports": "Sport",
    "arts": "Művészet",
    "marketplace": "Piactér",
    "aboutBp": "A BuildPulse-ról",
    "contribute": "Közreműködés",
    "advertise": "Hirdetés",
    "home": "Kezdőlap",
    "archive": "Archívum",
    "aiEditorial": "MI szerkesztőségi rendszer",
    "disclosure": "Közzététel",
    "privacy": "Adatvédelem",
    "terms": "Feltételek",
    "status": "Állapot",
    "tagline": "Globális technológia és digitális elemzés"
  },
  "cs": {
    "news": "Zprávy",
    "intelligence": "Analýzy",
    "community": "Komunita",
    "culture": "Kultura",
    "about": "O nás",
    "subscriptions": "Předplatné",
    "buildAi": "Tvořit s AI",
    "account": "Účet",
    "language": "Jazyk",
    "latest": "Nejnovější",
    "local": "Místní",
    "world": "Svět",
    "technology": "Technologie",
    "politics": "Politika",
    "economy": "Ekonomika",
    "markets": "Trhy",
    "methodology": "Metodologie",
    "social": "Sociální",
    "blogs": "Blogy",
    "people": "Lidé",
    "connections": "Spojení",
    "sports": "Sport",
    "arts": "Umění",
    "marketplace": "Tržiště",
    "aboutBp": "O BuildPulse",
    "contribute": "Přispět",
    "advertise": "Inzerovat",
    "home": "Domů",
    "archive": "Archiv",
    "aiEditorial": "Redakční systém AI",
    "disclosure": "Zveřejnění",
    "privacy": "Soukromí",
    "terms": "Podmínky",
    "status": "Stav",
    "tagline": "Globální technologie a digitální analýza"
  },
  "el": {
    "news": "Ειδήσεις",
    "intelligence": "Ανάλυση",
    "community": "Κοινότητα",
    "culture": "Πολιτισμός",
    "about": "Σχετικά",
    "subscriptions": "Συνδρομές",
    "buildAi": "Δημιουργία με AI",
    "account": "Λογαριασμός",
    "language": "Γλώσσα",
    "latest": "Τελευταία",
    "local": "Τοπικά",
    "world": "Κόσμος",
    "technology": "Τεχνολογία",
    "politics": "Πολιτική",
    "economy": "Οικονομία",
    "markets": "Αγορές",
    "methodology": "Μεθοδολογία",
    "social": "Κοινωνικά",
    "blogs": "Ιστολόγια",
    "people": "Άνθρωποι",
    "connections": "Συνδέσεις",
    "sports": "Αθλητισμός",
    "arts": "Τέχνες",
    "marketplace": "Αγορά",
    "aboutBp": "Σχετικά με το BuildPulse",
    "contribute": "Συνεισφορά",
    "advertise": "Διαφήμιση",
    "home": "Αρχική",
    "archive": "Αρχείο",
    "aiEditorial": "Σύστημα σύνταξης AI",
    "disclosure": "Γνωστοποιήσεις",
    "privacy": "Απόρρητο",
    "terms": "Όροι",
    "status": "Κατάσταση",
    "tagline": "Παγκόσμια τεχνολογία και ψηφιακή ανάλυση"
  },
  "bg": {
    "news": "Новини",
    "intelligence": "Анализи",
    "community": "Общност",
    "culture": "Култура",
    "about": "За нас",
    "subscriptions": "Абонаменти",
    "buildAi": "Създавай с AI",
    "account": "Профил",
    "language": "Език",
    "latest": "Последни",
    "local": "Местни",
    "world": "Свят",
    "technology": "Технологии",
    "politics": "Политика",
    "economy": "Икономика",
    "markets": "Пазари",
    "methodology": "Методология",
    "social": "Социално",
    "blogs": "Блогове",
    "people": "Хора",
    "connections": "Връзки",
    "sports": "Спорт",
    "arts": "Изкуства",
    "marketplace": "Пазар",
    "aboutBp": "За BuildPulse",
    "contribute": "Допринасяй",
    "advertise": "Реклама",
    "home": "Начало",
    "archive": "Архив",
    "aiEditorial": "AI редакционна система",
    "disclosure": "Оповестяване",
    "privacy": "Поверителност",
    "terms": "Условия",
    "status": "Статус",
    "tagline": "Глобални технологии и дигитален анализ"
  },
  "uk": {
    "news": "Новини",
    "intelligence": "Аналітика",
    "community": "Спільнота",
    "culture": "Культура",
    "about": "Про нас",
    "subscriptions": "Підписки",
    "buildAi": "Створити з ШІ",
    "account": "Обліковий запис",
    "language": "Мова",
    "latest": "Останнє",
    "local": "Місцеве",
    "world": "Світ",
    "technology": "Технології",
    "politics": "Політика",
    "economy": "Економіка",
    "markets": "Ринки",
    "methodology": "Методологія",
    "social": "Соціальне",
    "blogs": "Блоги",
    "people": "Люди",
    "connections": "Зв’язки",
    "sports": "Спорт",
    "arts": "Мистецтво",
    "marketplace": "Маркетплейс",
    "aboutBp": "Про BuildPulse",
    "contribute": "Долучитися",
    "advertise": "Реклама",
    "home": "Головна",
    "archive": "Архів",
    "aiEditorial": "Редакційна система ШІ",
    "disclosure": "Розкриття інформації",
    "privacy": "Конфіденційність",
    "terms": "Умови",
    "status": "Статус",
    "tagline": "Глобальні технології та цифрова аналітика"
  },
  "zh": {
    "news": "新闻",
    "intelligence": "情报",
    "community": "社区",
    "culture": "文化",
    "about": "关于",
    "subscriptions": "订阅",
    "buildAi": "用 AI 构建",
    "account": "账户",
    "language": "语言",
    "latest": "最新",
    "local": "本地",
    "world": "世界",
    "technology": "科技",
    "politics": "政治",
    "economy": "经济",
    "markets": "市场",
    "methodology": "方法论",
    "social": "社交",
    "blogs": "博客",
    "people": "人物",
    "connections": "连接",
    "sports": "体育",
    "arts": "艺术",
    "marketplace": "市场",
    "aboutBp": "关于 BuildPulse",
    "contribute": "投稿",
    "advertise": "广告",
    "home": "首页",
    "archive": "归档",
    "aiEditorial": "AI 编辑系统",
    "disclosure": "披露",
    "privacy": "隐私",
    "terms": "条款",
    "status": "状态",
    "tagline": "全球科技与数字情报"
  },
  "ja": {
    "news": "ニュース",
    "intelligence": "インテリジェンス",
    "community": "コミュニティ",
    "culture": "文化",
    "about": "概要",
    "subscriptions": "購読",
    "buildAi": "AIで構築",
    "account": "アカウント",
    "language": "言語",
    "latest": "最新",
    "local": "ローカル",
    "world": "世界",
    "technology": "テクノロジー",
    "politics": "政治",
    "economy": "経済",
    "markets": "市場",
    "methodology": "方法論",
    "social": "ソーシャル",
    "blogs": "ブログ",
    "people": "人物",
    "connections": "つながり",
    "sports": "スポーツ",
    "arts": "アート",
    "marketplace": "マーケット",
    "aboutBp": "BuildPulseについて",
    "contribute": "投稿",
    "advertise": "広告",
    "home": "ホーム",
    "archive": "アーカイブ",
    "aiEditorial": "AI編集システム",
    "disclosure": "開示",
    "privacy": "プライバシー",
    "terms": "利用規約",
    "status": "ステータス",
    "tagline": "グローバルテクノロジー＆デジタルインテリジェンス"
  },
  "ko": {
    "news": "뉴스",
    "intelligence": "인텔리전스",
    "community": "커뮤니티",
    "culture": "문화",
    "about": "소개",
    "subscriptions": "구독",
    "buildAi": "AI로 구축",
    "account": "계정",
    "language": "언어",
    "latest": "최신",
    "local": "지역",
    "world": "세계",
    "technology": "기술",
    "politics": "정치",
    "economy": "경제",
    "markets": "시장",
    "methodology": "방법론",
    "social": "소셜",
    "blogs": "블로그",
    "people": "인물",
    "connections": "연결",
    "sports": "스포츠",
    "arts": "예술",
    "marketplace": "마켓플레이스",
    "aboutBp": "BuildPulse 소개",
    "contribute": "기고",
    "advertise": "광고",
    "home": "홈",
    "archive": "아카이브",
    "aiEditorial": "AI 편집 시스템",
    "disclosure": "공개",
    "privacy": "개인정보 보호",
    "terms": "약관",
    "status": "상태",
    "tagline": "글로벌 기술 및 디지털 인텔리전스"
  },
  "ar": {
    "news": "الأخبار",
    "intelligence": "التحليلات",
    "community": "المجتمع",
    "culture": "الثقافة",
    "about": "حول",
    "subscriptions": "الاشتراكات",
    "buildAi": "أنشئ بالذكاء الاصطناعي",
    "account": "الحساب",
    "language": "اللغة",
    "latest": "الأحدث",
    "local": "محلي",
    "world": "العالم",
    "technology": "التقنية",
    "politics": "السياسة",
    "economy": "الاقتصاد",
    "markets": "الأسواق",
    "methodology": "المنهجية",
    "social": "اجتماعي",
    "blogs": "المدونات",
    "people": "الأشخاص",
    "connections": "الاتصالات",
    "sports": "الرياضة",
    "arts": "الفنون",
    "marketplace": "السوق",
    "aboutBp": "حول BuildPulse",
    "contribute": "ساهم",
    "advertise": "أعلن",
    "home": "الرئيسية",
    "archive": "الأرشيف",
    "aiEditorial": "نظام التحرير بالذكاء الاصطناعي",
    "disclosure": "الإفصاح",
    "privacy": "الخصوصية",
    "terms": "الشروط",
    "status": "الحالة",
    "tagline": "التكنولوجيا العالمية والاستخبارات الرقمية"
  },
  "hi": {
    "news": "समाचार",
    "intelligence": "विश्लेषण",
    "community": "समुदाय",
    "culture": "संस्कृति",
    "about": "परिचय",
    "subscriptions": "सदस्यताएँ",
    "buildAi": "AI के साथ बनाएँ",
    "account": "खाता",
    "language": "भाषा",
    "latest": "नवीनतम",
    "local": "स्थानीय",
    "world": "विश्व",
    "technology": "प्रौद्योगिकी",
    "politics": "राजनीति",
    "economy": "अर्थव्यवस्था",
    "markets": "बाज़ार",
    "methodology": "कार्यप्रणाली",
    "social": "सोशल",
    "blogs": "ब्लॉग",
    "people": "लोग",
    "connections": "कनेक्शन",
    "sports": "खेल",
    "arts": "कला",
    "marketplace": "मार्केटप्लेस",
    "aboutBp": "BuildPulse के बारे में",
    "contribute": "योगदान दें",
    "advertise": "विज्ञापन",
    "home": "होम",
    "archive": "अभिलेख",
    "aiEditorial": "AI संपादकीय प्रणाली",
    "disclosure": "प्रकटीकरण",
    "privacy": "गोपनीयता",
    "terms": "शर्तें",
    "status": "स्थिति",
    "tagline": "वैश्विक प्रौद्योगिकी और डिजिटल इंटेलिजेंस"
  }
} as const;
export function uiCopy(locale:string){return C[(locale in C?locale:"en") as UiLocale]}
