import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
function balanced(rows:any[],limit:number,per:number){const out:any[]=[],counts=new Map<string,number>();for(const x of rows){const k=x.source_id||"unknown",n=counts.get(k)||0;if(n>=per)continue;out.push(x);counts.set(k,n+1);if(out.length===limit)return out}for(const x of rows){if(out.some(y=>y.id===x.id))continue;out.push(x);if(out.length===limit)break}return out}
async function build(db:any,type:"daily"|"weekly"){
 const limit=type==="daily"?8:14,since=new Date(Date.now()-(type==="daily"?36:192)*3600000).toISOString(),date=new Date().toISOString().slice(0,10),slug=`${type}-${date}`,key=`${type}:en:${date}`;
 const {data:existing}=await db.from("buildpulse_editions").select("id,status,revision_number,founder_review_status,generation_error").eq("generation_key",key).maybeSingle();const regenerating=!!existing&&existing.status==="draft"&&existing.founder_review_status==="changes_requested"&&existing.generation_error==="quality_gate_non_core_lead";if(existing&&!regenerating)return {type,skipped:true,reason:"generation_already_claimed",editionId:existing.id,status:existing.status};
 const {data:stories,error}=await db.from("buildpulse_stories").select("id,title,summary,category,source_id,editorial_score,published_at,verified_at,verified_by,canonical_source_url").eq("verification_state","verified").neq("publication_state","withheld").gte("published_at",since).order("editorial_score",{ascending:false}).limit(limit*5);if(error)throw error;
 const ranked=stories||[];const core=["technology","cybersecurity","ai","blockchain","markets","economy"];const explicit=ranked.filter((x:any)=>core.includes(String(x.category||"").toLowerCase()));const keyword=ranked.filter((x:any)=>!["politics","local"].includes(String(x.category||"").toLowerCase())&&/(^|[^A-Za-zÀ-ž])(AI|artificial intelligence|yapay zeka|cyber|security|blockchain|crypto|digital|technology|teknoloji|semiconductor|cloud|data|robot|space|savunma|havacılık)([^A-Za-zÀ-ž]|$)/i.test(String(x.title||"")));const lead=explicit[0]||keyword[0];if(!lead)return {type,skipped:true,reason:"no_core_verified_lead"};const rest=ranked.filter((x:any)=>x.id!==lead?.id);const selected=lead?[lead,...balanced(rest,Math.max(0,limit-1),type==="daily"?2:3)]:[];if(!selected.length)return {type,skipped:true,reason:"no_verified_stories"};if(selected.some((x:any)=>!x.verified_at||!x.verified_by||!x.canonical_source_url))throw new Error("verified_story_missing_provenance");
 const subject=type==="daily"?`BuildPulse Daily — ${selected[0].title}`:`BuildPulse Weekly — ${selected[0].title}`,preheader=type==="daily"?"The essential AI, blockchain, markets and security signal.":"The week's connected view across digital infrastructure.",now=new Date().toISOString();
 let e:any;if(regenerating){await db.from("buildpulse_edition_stories").delete().eq("edition_id",existing.id);const {data:re,error:ru}=await db.from("buildpulse_editions").update({subject,preheader,slug,status:"draft",body_html:null,revision_number:existing.revision_number+1,founder_review_status:"pending",founder_approved_revision:null,approved_at:null,approved_by:null,founder_reviewed_at:null,founder_review_notes:null,generation_started_at:now,generation_completed_at:null,generation_error:null,generation_metadata:{strategy:"verified-score-source-balanced-v5-supabase-scheduler",generatedAt:now,storyCount:selected.length,regeneratedFromRevision:existing.revision_number}}).eq("id",existing.id).eq("revision_number",existing.revision_number).select("*").single();if(ru||!re)throw ru||new Error("edition_regeneration_failed");e=re;await db.from("buildpulse_review_events").insert({edition_id:e.id,action:"request_changes",actor:"edition-scheduler",notes:`Automated regeneration created revision ${e.revision_number} after the prior quality gate rejected a non-core lead.`})}else{const {data:ne,error:ie}=await db.from("buildpulse_editions").insert({edition_type:type,locale:"en",subject,preheader,slug,status:"draft",generation_key:key,generation_started_at:now,generation_metadata:{strategy:"verified-score-source-balanced-v5-supabase-scheduler",generatedAt:now,storyCount:selected.length}}).select("*").single();if(ie||!ne)throw ie||new Error("edition_create_failed");e=ne;}
 let pos=0;for(const s of selected){const {error:le}=await db.from("buildpulse_edition_stories").insert({edition_id:e.id,story_id:s.id,section:s.category||"lead",position:pos++});if(le)throw le}
 const blocks=selected.map((s:any)=>`<section><p style="font:700 12px Arial;letter-spacing:.12em;text-transform:uppercase;color:#64748b">${esc(s.category||"lead")}</p><h2 style="font:700 24px Arial;color:#0f172a">${esc(s.title)}</h2><p style="font:16px/1.65 Arial;color:#334155">${esc(s.summary||"")}</p><p><a href="${esc(s.canonical_source_url)}">Read source</a></p></section>`).join("");
 const html=`<!doctype html><html><body style="margin:0;background:#f8fafc"><main style="max-width:720px;margin:auto;padding:40px 24px;background:white"><p style="font:700 12px Arial;letter-spacing:.18em">TVK BUILDPULSE</p><h1 style="font:800 38px Arial;color:#0f172a">${esc(subject)}</h1><p style="font:16px Arial;color:#64748b">${esc(preheader)}</p>${blocks}<hr/><p style="font:12px/1.5 Arial;color:#64748b">Draft generated from verified source records. Founder review is required before publication or delivery.</p></main></body></html>`;
 const {error:u}=await db.from("buildpulse_editions").update({body_html:html,status:"review",founder_review_status:"pending",founder_approved_revision:null,generation_completed_at:new Date().toISOString(),generation_error:null,updated_at:new Date().toISOString()}).eq("id",e.id).eq("status","draft");if(u)throw u;
 return {type,skipped:false,editionId:e.id,slug,storyCount:selected.length,status:"review",approvalRequired:true};
}
Deno.serve(async(req)=>{const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});const {data:s}=await db.from("buildpulse_private_settings").select("value").eq("key","edition_scheduler_secret").maybeSingle();if(!s?.value||req.headers.get("x-buildpulse-scheduler-secret")!==s.value)return json({ok:false,error:"unauthorized"},401);const started=new Date().toISOString(),results:any[]=[];try{results.push(await build(db,"daily"));if(new Date().getUTCDay()===1)results.push(await build(db,"weekly"));await db.from("buildpulse_job_runs").insert({job_name:"edition-supabase",status:"ok",started_at:started,finished_at:new Date().toISOString(),metrics:{results}});return json({ok:true,deliveryTriggered:false,results})}catch(e){const m=e instanceof Error?e.message:"edition_generation_failed";await db.from("buildpulse_job_runs").insert({job_name:"edition-supabase",status:"failed",started_at:started,finished_at:new Date().toISOString(),error:m});return json({ok:false,error:m},500)}});
