import {NextRequest,NextResponse} from "next/server";import {cookies} from "next/headers";import {createClientSafe} from "@/utils/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function POST(req:NextRequest){const userDb=createClientSafe(await cookies());if(!userDb)return NextResponse.json({ok:false},{status:503});const {data:{user}}=await userDb.auth.getUser();if(!user)return NextResponse.json({ok:false,error:"auth_required"},{status:401});const db=createAdminClient();if(!db)return NextResponse.json({ok:false},{status:503});const b=await req.json().catch(()=>null),action=String(b?.action||""),targetUserId=String(b?.targetUserId||""),targetPostId=String(b?.targetPostId||""),reason=String(b?.reason||"").trim().slice(0,1000);
 if(["unblock","unmute"].includes(action)){const base=action==="unblock"?"block":"mute";if(!uuid.test(targetUserId))return NextResponse.json({ok:false,error:"invalid_target"},{status:400});await db.from("buildpulse_social_safety_actions").delete().eq("actor_id",user.id).eq("target_user_id",targetUserId).eq("action",base);return NextResponse.json({ok:true,active:false,action:base})}
 if(!["block","mute","report"].includes(action))return NextResponse.json({ok:false,error:"invalid_action"},{status:400});
 if(!uuid.test(targetUserId)&&!uuid.test(targetPostId))return NextResponse.json({ok:false,error:"target_required"},{status:400});
 if((action==="block"||action==="mute")&&(!uuid.test(targetUserId)||targetUserId===user.id))return NextResponse.json({ok:false,error:"invalid_target"},{status:400});
 if(action==="report"&&reason.length<3)return NextResponse.json({ok:false,error:"reason_required"},{status:400});
 let q=db.from("buildpulse_social_safety_actions").select("id").eq("actor_id",user.id).eq("action",action);q=uuid.test(targetUserId)?q.eq("target_user_id",targetUserId):q.is("target_user_id",null);q=uuid.test(targetPostId)?q.eq("target_post_id",targetPostId):q.is("target_post_id",null);const {data:existing}=await q.limit(1).maybeSingle();if(existing)return NextResponse.json({ok:true,idempotent:true,active:true});
 const {data,error}=await db.from("buildpulse_social_safety_actions").insert({actor_id:user.id,target_user_id:uuid.test(targetUserId)?targetUserId:null,target_post_id:uuid.test(targetPostId)?targetPostId:null,action,reason:reason||null}).select("id").single();if(error)return NextResponse.json({ok:false,error:"safety_action_failed"},{status:500});return NextResponse.json({ok:true,id:data.id,active:true})}