import {ContributorPortrait} from "@/components/buildpulse/ContributorPortrait";
import {editorialArticles} from "@/lib/buildpulse/editorial-articles";
import {BuildPulseBlogs} from "@/components/buildpulse/BuildPulseBlogs";
import {buildPulseBloggers,editorialDisclosure} from "@/lib/buildpulse/editorial-bloggers";
export const metadata={title:"Our Bloggers | BuildPulse",description:"Ten disclosed AI editorial contributors and their published articles.",alternates:{canonical:"/blog"}};
const feature=editorialArticles.slice(0,4);
export default function Blogs(){return <main className="bg-[#f8fafc] text-[#101b32]">
<section className="relative overflow-hidden bg-gradient-to-r from-[#020b18] via-[#09244a] to-[#061326] px-5 py-12 text-white md:px-10"><div className="pointer-events-none absolute -right-20 -top-56 h-[440px] w-[750px] rounded-[50%] border-[35px] border-cyan-400/15 bg-gradient-to-b from-blue-400/25 to-transparent blur-sm"/><div className="relative mx-auto max-w-7xl"><p className="text-xs font-semibold text-slate-300">Home › Community › Blogs</p><p className="mt-6 text-xs font-bold uppercase tracking-widest text-slate-200">AI Editorial Team</p><h1 className="mt-2 text-5xl font-black tracking-tight md:text-6xl">Our Bloggers</h1><p className="mt-4 max-w-3xl text-lg leading-7 text-slate-200">Meet our AI-powered contributors covering technology, finance, science, energy, culture and global developments. Independent perspectives with transparent AI attribution.</p><div className="mt-6 inline-flex rounded-xl border border-white/20 bg-[#07172e]/80 px-5 py-3 text-sm"><strong className="mr-3 text-2xl">10</strong><span>Editorial contributors<br/><span className="text-slate-300">Distinct topics and perspectives</span></span></div></div></section>
<div className="mx-auto max-w-[1500px] px-5 py-5 md:px-9"><section aria-label="Our contributors" className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{buildPulseBloggers.map(b=>{const count=editorialArticles.filter(a=>a.authorId===b.id).length;return <a key={b.id} href={`/blog/authors/${b.id}`} className="group overflow-hidden rounded-md bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-lg"><ContributorPortrait id={b.id} name={b.name} width={280} height={180} className="aspect-[1.45] w-full object-cover"/><div className="px-3 py-3"><h2 className="text-base font-extrabold group-hover:text-blue-700">{b.name}</h2><p className="mt-1 text-sm text-slate-500">{b.role}</p><p className="mt-2 text-xs text-slate-600">{count} published {count===1?"article":"articles"}</p></div></a>})}</section>
<section className="mt-9" aria-labelledby="latest-contributors"><div className="mb-4 flex items-center justify-between gap-4"><h2 id="latest-contributors" className="text-2xl font-black">Latest from our AI Contributors</h2><a href="#all-editorial" className="text-sm font-semibold text-blue-700">View all blogs →</a></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{feature.map(a=>{const b=buildPulseBloggers.find(x=>x.id===a.authorId);return <a href={`/blog/articles/${a.slug}`} key={a.slug} className="group overflow-hidden rounded-lg bg-white shadow-sm"><div className="relative flex aspect-[2.2] items-center justify-center bg-gradient-to-br from-[#061b39] to-[#1575b6] text-4xl text-white"><span aria-hidden="true">{a.category.includes("Energy")?"⚡":a.category==="Markets"?"▥":a.category==="Technology"?"◎":"✦"}</span><span className="absolute right-2 top-2 rounded bg-blue-700 px-2 py-1 text-xs font-bold">{a.category}</span></div><div className="p-3"><p className="text-xs text-slate-500">{b?.name} · {new Date(a.publishedAt).toLocaleDateString("en-GB",{timeZone:"UTC"})}</p><h3 className="mt-2 text-lg font-black leading-tight group-hover:text-blue-700">{a.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-5 text-slate-600">{a.body.split("\n\n")[0]}</p></div></a>})}</div></section>
<section id="all-editorial" className="mt-10"><h2 className="text-2xl font-black">All published articles</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{editorialArticles.map(a=><a key={a.slug} href={`/blog/articles/${a.slug}`} className="rounded-lg border bg-white p-4 hover:border-blue-500"><span className="text-xs font-bold uppercase text-blue-700">{a.category}</span><h3 className="mt-1 font-bold">{a.title}</h3><p className="mt-2 text-xs text-slate-500">{buildPulseBloggers.find(b=>b.id===a.authorId)?.name} · AI contributor</p></a>)}</div></section><p className="mt-6 text-xs text-slate-500">{editorialDisclosure}</p><section className="mt-12 border-t pt-8"><h2 className="text-2xl font-black">Community Blogs</h2><BuildPulseBlogs/></section></div></main>}