-- BuildPulse accounting, tax evidence and double-entry ledger core.
-- Tax is determined per transaction from registered jurisdictions, customer status/location and product classification; never from a hard-coded country-rate table.
create table if not exists public.buildpulse_accounting_entities(id uuid primary key default gen_random_uuid(),legal_name text not null,company_number text,country_code text not null check(char_length(country_code)=2),base_currency text not null default 'GBP',vat_number text,tax_registered boolean not null default false,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists buildpulse_one_default_entity on public.buildpulse_accounting_entities(is_default) where is_default;
create table if not exists public.buildpulse_tax_registrations(id uuid primary key default gen_random_uuid(),entity_id uuid not null references public.buildpulse_accounting_entities(id) on delete cascade,jurisdiction text not null,tax_type text not null,registration_number text,status text not null default 'planned' check(status in ('planned','pending','active','ended')),scheme text,effective_from date,effective_to date,provider_registration_id text,created_at timestamptz not null default now(),unique(entity_id,jurisdiction,tax_type,registration_number));
create table if not exists public.buildpulse_accounting_customers(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,stripe_customer_id text unique,email text,legal_name text,business_customer boolean not null default false,country_code text,tax_id_type text,tax_id_value text,tax_id_status text not null default 'unverified',billing_address jsonb not null default '{}'::jsonb,location_evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.buildpulse_accounting_documents(id uuid primary key default gen_random_uuid(),entity_id uuid not null references public.buildpulse_accounting_entities(id),customer_id uuid references public.buildpulse_accounting_customers(id),document_type text not null check(document_type in ('invoice','credit_note','receipt')),document_number text not null unique,currency text not null,net_amount numeric(20,6) not null default 0,tax_amount numeric(20,6) not null default 0,gross_amount numeric(20,6) not null default 0,tax_jurisdiction text,tax_treatment text,tax_rate numeric(10,6),reverse_charge boolean not null default false,stripe_invoice_id text unique,stripe_payment_intent_id text,stripe_subscription_id text,provider_pdf_url text,status text not null default 'draft',issued_at timestamptz,due_at timestamptz,paid_at timestamptz,immutable_snapshot jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.buildpulse_ledger_accounts(code text primary key,name text not null,account_type text not null check(account_type in ('asset','liability','equity','income','expense')),active boolean not null default true);
create table if not exists public.buildpulse_journal_entries(id uuid primary key default gen_random_uuid(),entity_id uuid not null references public.buildpulse_accounting_entities(id),entry_date date not null,source_type text not null,source_id text,description text,currency text not null default 'GBP',fx_rate_to_base numeric(20,10) not null default 1,status text not null default 'posted' check(status in ('draft','posted','reversed')),created_at timestamptz not null default now(),unique(entity_id,source_type,source_id));
create table if not exists public.buildpulse_journal_lines(id uuid primary key default gen_random_uuid(),entry_id uuid not null references public.buildpulse_journal_entries(id) on delete cascade,account_code text not null references public.buildpulse_ledger_accounts(code),debit numeric(20,6) not null default 0,credit numeric(20,6) not null default 0,tax_jurisdiction text,metadata jsonb not null default '{}'::jsonb,check(debit>=0 and credit>=0 and not(debit>0 and credit>0)));
create table if not exists public.buildpulse_accounting_periods(id uuid primary key default gen_random_uuid(),entity_id uuid not null references public.buildpulse_accounting_entities(id),period_start date not null,period_end date not null,status text not null default 'open' check(status in ('open','review','closed')),closed_at timestamptz,unique(entity_id,period_start,period_end));
insert into public.buildpulse_ledger_accounts(code,name,account_type) values('1000','Stripe / cash clearing','asset'),('1100','Accounts receivable','asset'),('2000','Tax payable','liability'),('2100','Deferred subscription revenue','liability'),('4000','Subscription revenue','income'),('4010','Advertising revenue','income'),('4020','Contributor revenue','income'),('4030','Marketplace revenue','income'),('5000','Payment processing fees','expense'),('5100','Refunds and chargebacks','expense') on conflict(code) do nothing;
insert into public.buildpulse_accounting_entities(legal_name,company_number,country_code,base_currency,is_default) select 'TVK Labs & Technologies LTD','16481808','GB','GBP',true where not exists(select 1 from public.buildpulse_accounting_entities where is_default);
alter table public.buildpulse_accounting_entities enable row level security;alter table public.buildpulse_tax_registrations enable row level security;alter table public.buildpulse_accounting_customers enable row level security;alter table public.buildpulse_accounting_documents enable row level security;alter table public.buildpulse_ledger_accounts enable row level security;alter table public.buildpulse_journal_entries enable row level security;alter table public.buildpulse_journal_lines enable row level security;alter table public.buildpulse_accounting_periods enable row level security;
create policy "customer reads own accounting profile" on public.buildpulse_accounting_customers for select to authenticated using(user_id=auth.uid());
create policy "customer reads own accounting documents" on public.buildpulse_accounting_documents for select to authenticated using(customer_id in(select id from public.buildpulse_accounting_customers where user_id=auth.uid()));