create table if not exists public.buildpulse_agents(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,domain text not null,autonomy_level text not null default 'draft' check(autonomy_level in ('observe','draft','execute_low_risk','approval_required')),enabled boolean not null default true,description text,allowed_actions text[] not null default '{}'::text[],blocked_actions text[] not null default '{}'::text[],schedule_hint text,config jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.buildpulse_agent_runs(id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.buildpulse_agents(id),trigger_type text not null,triggered_by uuid references auth.users(id) on delete set null,status text not null default 'queued' check(status in ('queued','running','awaiting_approval','approved','rejected','completed','failed','cancelled')),proposed_actions jsonb not null default '[]'::jsonb,executed_actions jsonb not null default '[]'::jsonb,summary text,error text,started_at timestamptz,finished_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.buildpulse_agent_approvals(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.buildpulse_agent_runs(id) on delete cascade,action_key text not null,risk_level text not null check(risk_level in ('low','medium','high','critical')),state text not null default 'pending' check(state in ('pending','approved','rejected','expired')),requested_at timestamptz not null default now(),decided_at timestamptz,decided_by uuid references auth.users(id) on delete set null,notes text,unique(run_id,action_key));
alter table public.buildpulse_agents enable row level security;alter table public.buildpulse_agent_runs enable row level security;alter table public.buildpulse_agent_approvals enable row level security;revoke all on public.buildpulse_agents from anon,authenticated;revoke all on public.buildpulse_agent_runs from anon,authenticated;revoke all on public.buildpulse_agent_approvals from anon,authenticated;grant all on public.buildpulse_agents to service_role;grant all on public.buildpulse_agent_runs to service_role;grant all on public.buildpulse_agent_approvals to service_role;
insert into public.buildpulse_agents(code,name,domain,autonomy_level,description,allowed_actions,blocked_actions,schedule_hint) values
('news-desk','News Desk Agent','editorial','draft','Ingests, deduplicates, scores and drafts source-grounded news.',array['ingest','deduplicate','score','draft','request_review'],array['verify_fact','publish_unverified','delete_published'],'continuous'),
('localization','Localization Agent','localization','draft','Produces locale drafts and detects untranslated UI/content.',array['detect_locale_gaps','draft_translation','localize_metadata'],array['publish_factual_translation_without_review'],'hourly'),
('social-ops','Social Operations Agent','social','execute_low_risk','Queues approved content, detects abuse signals and prepares engagement summaries.',array['schedule_approved','classify','summarize','flag'],array['impersonate','silently_remove','change_identity'],'continuous'),
('finance-reconcile','Finance Reconciliation Agent','finance','draft','Reconciles provider events with invoices and ledger and flags discrepancies.',array['reconcile','draft_journal','flag_variance','prepare_report'],array['move_money','file_tax_return','change_tax_registration'],'daily'),
('platform-ops','Platform Operations Agent','operations','execute_low_risk','Checks jobs, integrations, delivery and platform health.',array['health_check','retry_idempotent_job','raise_incident'],array['rotate_secret_without_approval','change_roles','delete_data'],'continuous'),
('moderation','Safety Moderation Agent','safety','draft','Prioritizes reports and proposes moderation actions.',array['classify_report','prioritize','propose_action'],array['permanent_ban_without_review','law_enforcement_disclosure'],'continuous')
on conflict(code) do update set name=excluded.name,description=excluded.description,allowed_actions=excluded.allowed_actions,blocked_actions=excluded.blocked_actions,schedule_hint=excluded.schedule_hint;