alter table public.buildpulse_agent_schedules add column if not exists claim_token uuid;
alter table public.buildpulse_agent_schedules add column if not exists claimed_at timestamptz;
alter table public.buildpulse_agent_schedules add column if not exists last_run_status text check(last_run_status is null or last_run_status in ('running','completed','failed'));
create or replace function public.buildpulse_claim_due_agent_schedules(p_limit integer default 30) returns table(schedule_id uuid,agent_code text,input_template text,claim_token uuid) language plpgsql security definer set search_path=public as $$
begin
 return query with due as (select s.id from public.buildpulse_agent_schedules s where s.enabled=true and s.cadence<>'manual' and coalesce(s.next_run_at,now())<=now() and (s.claimed_at is null or s.claimed_at<now()-interval '30 minutes') order by coalesce(s.next_run_at,now()) for update skip locked limit greatest(1,least(p_limit,50))), claimed as (update public.buildpulse_agent_schedules s set claim_token=gen_random_uuid(),claimed_at=now(),last_run_at=now(),last_run_status='running',next_run_at=case s.cadence when 'hourly' then now()+interval '1 hour' when 'daily' then now()+interval '1 day' when 'weekly' then now()+interval '7 days' else s.next_run_at end,updated_at=now() from due d where s.id=d.id returning s.id,s.agent_id,s.input_template,s.claim_token) select c.id,a.code,c.input_template,c.claim_token from claimed c join public.buildpulse_agents a on a.id=c.agent_id where a.enabled=true;
end $$;
revoke all on function public.buildpulse_claim_due_agent_schedules(integer) from public;grant execute on function public.buildpulse_claim_due_agent_schedules(integer) to service_role;
create or replace function public.buildpulse_finish_agent_schedule(p_schedule_id uuid,p_claim_token uuid,p_status text) returns boolean language plpgsql security definer set search_path=public as $$
declare changed integer;begin if p_status not in ('completed','failed') then raise exception 'invalid status';end if;update public.buildpulse_agent_schedules set last_run_status=p_status,claim_token=null,claimed_at=null,updated_at=now() where id=p_schedule_id and claim_token=p_claim_token;get diagnostics changed=row_count;return changed=1;end $$;
revoke all on function public.buildpulse_finish_agent_schedule(uuid,uuid,text) from public;grant execute on function public.buildpulse_finish_agent_schedule(uuid,uuid,text) to service_role;