insert into public.buildpulse_crypto_inventory(system_area,crypto_purpose,current_algorithm,target_algorithm,pq_status,owner,risk_notes,last_reviewed_at) values
('social-messaging','message key establishment','Not production-enabled; e2ee-v1 is scaffolding only','Audited mature hybrid classical + ML-KEM protocol','planned','security','Do not enable private messaging or market quantum security until protocol, key lifecycle and independent review are complete.',now()),
('social-messaging','identity signatures','Not production-enabled','Audited classical + ML-DSA hybrid where protocol support is mature','planned','security','No custom cryptographic protocol.',now()),
('edge-transport','TLS key establishment','Vercel-managed TLS; PQ capability not independently verified','Provider-supported hybrid post-quantum TLS after verification','planned','infrastructure','Verify actual edge TLS capability before making PQ claims.',now()),
('database','at-rest encryption','Supabase-managed; exact primitive not asserted by BuildPulse','Provider-managed strong symmetric encryption with documented key lifecycle','inventory','infrastructure','Obtain provider documentation and key-management evidence.',now()),
('authentication','sessions and credentials','Supabase Auth managed','Provider-supported crypto agility + passkeys/MFA','inventory','security','AAL2 is enforced for workforce; passkey policy requires runtime/provider enforcement verification.',now()),
('stripe-webhook','event authentication','HMAC-SHA-256','HMAC-SHA-256 with strong secret rotation','not_applicable','payments','Symmetric MAC is not replaced merely for PQ branding; rotate secrets and maintain sufficient entropy.',now()),
('internal-secrets','API and service credentials','Managed environment secrets; cipher implementation provider-managed','Central secrets management, rotation and least privilege','inventory','security','Never store provider secrets in Git.',now()),
('backups','backup encryption and recovery','Not independently verified','Documented encrypted backup + offline/off-site recovery with tested key rotation','planned','infrastructure','Complete backup cryptographic and recovery evidence.',now())
on conflict(system_area,crypto_purpose) do update set current_algorithm=excluded.current_algorithm,target_algorithm=excluded.target_algorithm,pq_status=excluded.pq_status,owner=excluded.owner,risk_notes=excluded.risk_notes,last_reviewed_at=excluded.last_reviewed_at;