-- Specialized newsroom agent mesh for fast, source-grounded BuildPulse coverage.
-- Agent rows are service-role only through the existing control-plane RLS/grants.
insert into public.buildpulse_agents(code,name,domain,autonomy_level,description,allowed_actions,blocked_actions,schedule_hint,config) values
('desk-world','World News Agent','editorial','draft','Continuously triages verified world-source records for freshness, importance and provenance.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_fact','remove_provenance'],'continuous','{"desk":"world","priority":"breaking"}'),
('desk-politics','Politics News Agent','editorial','draft','Continuously triages verified politics records and preserves primary-source provenance.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_fact','partisan_advocacy'],'continuous','{"desk":"politics","priority":"breaking"}'),
('desk-economy','Economy News Agent','editorial','draft','Tracks economy and digital-economy records with timestamps and source provenance.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_market_data','investment_instruction'],'continuous','{"desk":"economy","categories":["economy","digital-economy"]}'),
('desk-ai','AI News Agent','editorial','draft','Tracks AI developments and prioritizes primary technical and institutional sources.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_capability','remove_provenance'],'continuous','{"desk":"ai"}'),
('desk-blockchain','Blockchain News Agent','editorial','draft','Tracks blockchain and digital-asset infrastructure records.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_listing','investment_instruction'],'continuous','{"desk":"blockchain"}'),
('desk-security','Security News Agent','editorial','draft','Tracks cybersecurity records with heightened provenance and uncertainty requirements.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','operationalize_exploit','invent_attribution'],'continuous','{"desk":"security"}'),
('desk-sports','Sports News Agent','editorial','draft','Tracks verified sports feeds for fast event and result coverage.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_result','remove_provenance'],'continuous','{"desk":"sports"}'),
('desk-science','Science News Agent','editorial','draft','Tracks official science sources and prioritizes new research and discoveries.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_finding','overstate_research'],'continuous','{"desk":"science"}'),
('desk-health','Health News Agent','editorial','draft','Tracks verified health news while avoiding unsupported medical claims.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','medical_diagnosis','invent_claim'],'continuous','{"desk":"health"}'),
('desk-culture','Culture News Agent','editorial','draft','Tracks culture and arts source records.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_quote','remove_provenance'],'continuous','{"desk":"culture"}'),
('desk-life','Life News Agent','editorial','draft','Tracks verified life and human-interest records.',array['triage','deduplicate','score','draft','request_review'],array['publish_unverified','invent_quote','remove_provenance'],'continuous','{"desk":"life"}'),
('breaking-news','Breaking News Priority Agent','editorial','draft','Ranks newly ingested verified records by freshness, significance and corroboration for immediate desk attention.',array['rank','cluster','flag_breaking','request_review'],array['publish_unverified','invent_fact','bypass_review'],'continuous','{"latency_target_seconds":120}'),
('source-freshness','Source Freshness Agent','operations','execute_low_risk','Monitors source fetch recency, failures and stale feeds and raises bounded operational flags.',array['inspect_source_health','flag_stale','summarize_failures'],array['change_credentials','disable_source_without_evidence','publish'],'continuous','{"stale_minutes":90}'),
('news-dedupe','News Deduplication Agent','editorial','execute_low_risk','Clusters duplicate and near-duplicate incoming stories while preserving canonical provenance.',array['detect_duplicate','cluster','recommend_canonical'],array['delete_published','erase_provenance','merge_unrelated'],'continuous','{"preserve_all_sources":true}'),
('provenance-check','Provenance Verification Agent','editorial','draft','Checks canonical URL, source identity, timestamps and evidence completeness before publication review.',array['check_provenance','flag_missing_evidence','request_review'],array['self_verify_unsupported_fact','publish','invent_source'],'continuous','{"fail_closed":true}'),
('media-enrichment','Media Enrichment Agent','editorial','draft','Finds source-provided article imagery and media metadata with attribution and rights-safe provenance.',array['extract_source_media','validate_media_url','draft_alt_text','record_attribution'],array['generate_fake_news_photo','strip_attribution','copy_unlicensed_media'],'continuous','{"source_media_only":true}'),
('seo-news','News SEO Agent','editorial','draft','Prepares source-grounded metadata, structured-data suggestions and internal linking for verified stories.',array['draft_metadata','suggest_internal_links','check_schema'],array['keyword_stuffing','change_facts','publish_unverified'],'continuous','{"facts_from_story_only":true}'),
('publication-health','Publication Health Agent','operations','execute_low_risk','Monitors desk freshness, empty pages, route errors, sitemap coverage and publication latency.',array['check_routes','check_freshness','flag_empty_desk','summarize_latency'],array['deploy','change_secrets','publish'],'continuous','{"freshness_target_minutes":15}')
on conflict(code) do update set name=excluded.name,domain=excluded.domain,autonomy_level=excluded.autonomy_level,description=excluded.description,allowed_actions=excluded.allowed_actions,blocked_actions=excluded.blocked_actions,schedule_hint=excluded.schedule_hint,config=excluded.config,enabled=true,updated_at=now();

insert into public.buildpulse_agent_schedules(agent_id,name,cadence,input_template,next_run_at)
select id,'rapid-newsroom','hourly',
case
 when code like 'desk-%' then 'Review newly verified BuildPulse stories for your configured desk since the previous run. Prioritize newest material, breaking significance, source provenance, useful detail and available source imagery. Deduplicate aggressively. Produce a source-grounded editorial proposal only; never invent missing facts or bypass publication review.'
 when code='breaking-news' then 'Rank newly verified stories across all desks by freshness, significance and corroboration. Flag only evidence-backed breaking candidates and preserve source URLs and timestamps.'
 when code='source-freshness' then 'Inspect enabled BuildPulse sources for stale fetches, repeated failures and abnormal latency. Produce bounded operational flags and recovery recommendations without changing credentials.'
 when code='news-dedupe' then 'Inspect recent incoming stories for duplicate or near-duplicate coverage. Preserve every source relationship and recommend canonical clusters; do not delete published evidence.'
 when code='provenance-check' then 'Inspect recent publication candidates for canonical source URL, source identity, timestamps and verification evidence. Fail closed on missing provenance.'
 when code='media-enrichment' then 'Inspect recent verified stories missing imagery or media metadata. Use only source-provided or rights-safe media references, preserve attribution and propose useful alt text.'
 when code='seo-news' then 'Prepare factual metadata, structured-data suggestions and internal links for newly verified stories using only facts already present in verified story evidence.'
 when code='publication-health' then 'Inspect desk freshness, empty desks, route health, sitemap coverage and publication latency. Flag stale or broken surfaces with concrete evidence.'
end,now()
from public.buildpulse_agents
where code like 'desk-%' or code in ('breaking-news','source-freshness','news-dedupe','provenance-check','media-enrichment','seo-news','publication-health')
on conflict(agent_id,name) do update set enabled=true,input_template=excluded.input_template,next_run_at=least(public.buildpulse_agent_schedules.next_run_at,now()),updated_at=now();
