import Link from "next/link";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {createClientSafe} from "@/utils/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";

export const metadata={title:"Account | BuildPulse",robots:{index:false,follow:false}};

export default async function AccountPage(){
 const supabase=createClientSafe(await cookies());if(!supabase)redirect("/auth?next=/account");
 const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth?next=/account");
 {const admin=createAdminClient();if(admin)await admin.rpc("buildpulse_claim_own_subscriptions_for_user",{p_user_id:user.id,p_email:String(user.email||"")});}
 const db=createAdminClient();if(!db)throw new Error("Account service unavailable");
 const [{data:subs},{data:cryptoTerms},{data:customer},{data:social},{count:contrib},{count:arts},{count:ads}]=await Promise.all([
  db.from("buildpulse_intelligence_subscriptions").select("id,plan_code,billing_interval,status,current_period_end,cancelled_at,created_at,stripe_subscription_id").or(`user_id.eq.${user.id},email.eq.${String(user.email).toLowerCase()}`).order("created_at",{ascending:false}).limit(5),
  db.from("buildpulse_subscription_crypto_payments").select("id,plan_code,billing_interval,asset,network,usd_amount,state,tx_hash,confirmed_at,entitlement_end,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(10),
  db.from("buildpulse_accounting_customers").select("id,legal_name,business_customer,country_code,tax_id_status,billing_address").or(`user_id.eq.${user.id},email.eq.${String(user.email).toLowerCase()}`).limit(1).maybeSingle(),
  db.from("buildpulse_social_profiles").select("handle,display_name,account_type,verified_kind").eq("user_id",user.id).maybeSingle(),
  db.from("buildpulse_contributor_submissions").select("id",{head:true,count:"exact"}).eq("user_id",user.id),
  db.from("buildpulse_art_submissions").select("id",{head:true,count:"exact"}).eq("user_id",user.id),
  db.from("buildpulse_ad_orders").select("id",{head:true,count:"exact"}).eq("user_id",user.id)
 ]);
 const docs=customer?.id?(await db.from("buildpulse_accounting_documents").select("id,document_number,document_type,currency,gross_amount,status,issued_at,paid_at,provider_pdf_url").eq("customer_id",customer.id).order("created_at",{ascending:false}).limit(20)).data??[]:[];
 const active=(subs??[]).find((s:any)=>["active","trialing"].includes(s.status));const cryptoActive=(cryptoTerms??[]).find((p:any)=>p.state==="confirmed"&&p.entitlement_end&&new Date(p.entitlement_end)>new Date());const isStripe=Boolean(active?.stripe_subscription_id);
 const cards=[["Intelligence",active?active.plan_code:"No active plan",active?"/account/intelligence":"/subscriptions"],["Invoices & receipts",docs.length,"/account#documents"],["Contributor submissions",contrib??0,"/contribute"],["Art submissions",arts??0,"/arts/contribute"],["Advertising campaigns",ads??0,"/advertiser"],["Social",social?("@"+social.handle):"Set up profile",social?"/account/social":"/social"]];
 return <main className="min-h-screen bg-[#fbfaf6] text-[#17202a]"><div className="mx-auto max-w-[1280px] px-5 py-12">
  <div className="border-b border-black/15 pb-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[#0b6b63]">BuildPulse Account</p><h1 className="mt-2 text-4xl font-black tracking-tight">Your client portal</h1><p className="mt-3 text-sm text-slate-600">{user.email}</p></div>
  <section className="mt-7 rounded-3xl border border-black/10 bg-[#eef4f1] p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Choose your workspace</p><h2 className="mt-2 text-2xl font-black">One identity, clearly separated roles.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Customer services, subscriptions, contributor work, advertising and internal workforce access have separate entry points and authorization rules. A user only sees capabilities granted to their account.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link href="/account/intelligence" className="rounded-xl bg-white p-4 font-black">Subscriber →</Link><Link href="/contribute" className="rounded-xl bg-white p-4 font-black">Contributor →</Link><Link href="/advertiser" className="rounded-xl bg-white p-4 font-black">Advertiser →</Link><Link href="/workforce/control" className="rounded-xl bg-white p-4 font-black">BuildPulse Workforce →</Link></div></section><section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([n,v,h])=><Link key={String(n)} href={String(h)} className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{n}</p><p className="mt-2 text-xl font-black">{v}</p></Link>)}</section>
  <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Subscription</p><h2 className="mt-1 text-2xl font-black">BuildPulse Intelligence</h2>{active?<div className="mt-4 text-sm leading-7"><p><b>Plan:</b> {active.plan_code}</p><p><b>Billing:</b> {active.billing_interval}{cryptoActive&&!isStripe?" · prepaid crypto term":""}</p><p><b>Status:</b> {active.status}</p>{active.current_period_end&&<p><b>Current period:</b> through {new Date(active.current_period_end).toLocaleDateString("en-GB")}</p>}{isStripe?<a href="https://billing.stripe.com/p/login/dRm14nenPebH12FfN5gA800" className="mt-4 inline-block rounded-full border border-slate-300 px-4 py-2 text-xs font-black">Manage billing in Stripe</a>:<Link href="/subscriptions" className="mt-4 inline-block rounded-full border border-slate-300 px-4 py-2 text-xs font-black">Renew prepaid term</Link>}</div>:<p className="mt-4 text-sm text-slate-600">No active Intelligence entitlement is linked to this account.</p>}</div>
  <div className="rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Billing profile</p><h2 className="mt-1 text-2xl font-black">{customer?.legal_name||"Personal account"}</h2><div className="mt-4 text-sm leading-7 text-slate-600"><p>Country: {customer?.country_code||"Not supplied"}</p><p>Account type: {customer?.business_customer?"Business":"Consumer / not classified as business"}</p><p>Tax ID: {customer?.tax_id_status||"Not supplied"}</p></div><p className="mt-4 text-xs leading-5 text-slate-500">Tax treatment is determined from validated billing/tax evidence and applicable registrations, not from browser language or location alone.</p></div></section>
  <section id="documents" className="mt-8 rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Documents</p><h2 className="mt-1 text-2xl font-black">Invoices, receipts & credit notes</h2>{docs.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Document</th><th>Type</th><th>Amount</th><th>Status</th><th>Issued</th></tr></thead><tbody>{docs.map((d:any)=><tr key={d.id} className="border-b"><td className="py-4 font-bold">{d.provider_pdf_url?<a href={d.provider_pdf_url} target="_blank" rel="noreferrer" className="underline">{d.document_number}</a>:d.document_number}</td><td>{d.document_type}</td><td>{d.currency} {Number(d.gross_amount).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{d.status}</td><td>{d.issued_at?new Date(d.issued_at).toLocaleDateString("en-GB"):"—"}</td></tr>)}</tbody></table></div>:<p className="mt-4 text-sm text-slate-600">No accounting documents are linked to this account yet.</p>}</section>{(cryptoTerms??[]).length>0&&<section className="mt-8 rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#0b6b63]">Crypto payments</p><h2 className="mt-1 text-2xl font-black">Prepaid Intelligence terms</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Plan</th><th>Term</th><th>Payment</th><th>Status</th><th>Entitlement</th></tr></thead><tbody>{(cryptoTerms??[]).map((p:any)=><tr key={p.id} className="border-b"><td className="py-4 font-bold">{p.plan_code}</td><td>{p.billing_interval}</td><td>{p.asset} · {p.network} · USD {Number(p.usd_amount).toFixed(2)}</td><td>{p.state}</td><td>{p.entitlement_end?new Date(p.entitlement_end).toLocaleDateString("en-GB"):"—"}</td></tr>)}</tbody></table></div></section>}
 </div></main>
}